// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/resources/change_status.proto" (package "google.ads.googleads.v11.resources", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ChangeStatusOperationEnum_ChangeStatusOperation } from "../enums/change_status_operation";
import { ChangeStatusResourceTypeEnum_ChangeStatusResourceType } from "../enums/change_status_resource_type";
// Proto file describing the Change Status resource.

/**
 * Describes the status of returned resource. ChangeStatus could have up to 3
 * minutes delay to reflect a new change.
 *
 * @generated from protobuf message google.ads.googleads.v11.resources.ChangeStatus
 */
export interface ChangeStatus {
    /**
     * Output only. The resource name of the change status.
     * Change status resource names have the form:
     *
     * `customers/{customer_id}/changeStatus/{change_status_id}`
     *
     * @generated from protobuf field: string resource_name = 1;
     */
    resourceName: string;
    /**
     * Output only. Time at which the most recent change has occurred on this resource.
     *
     * @generated from protobuf field: optional string last_change_date_time = 24;
     */
    lastChangeDateTime?: string;
    /**
     * Output only. Represents the type of the changed resource. This dictates what fields
     * will be set. For example, for AD_GROUP, campaign and ad_group fields will
     * be set.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.ChangeStatusResourceTypeEnum.ChangeStatusResourceType resource_type = 4;
     */
    resourceType: ChangeStatusResourceTypeEnum_ChangeStatusResourceType;
    /**
     * Output only. The Campaign affected by this change.
     *
     * @generated from protobuf field: optional string campaign = 17;
     */
    campaign?: string;
    /**
     * Output only. The AdGroup affected by this change.
     *
     * @generated from protobuf field: optional string ad_group = 18;
     */
    adGroup?: string;
    /**
     * Output only. Represents the status of the changed resource.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.ChangeStatusOperationEnum.ChangeStatusOperation resource_status = 8;
     */
    resourceStatus: ChangeStatusOperationEnum_ChangeStatusOperation;
    /**
     * Output only. The AdGroupAd affected by this change.
     *
     * @generated from protobuf field: optional string ad_group_ad = 25;
     */
    adGroupAd?: string;
    /**
     * Output only. The AdGroupCriterion affected by this change.
     *
     * @generated from protobuf field: optional string ad_group_criterion = 26;
     */
    adGroupCriterion?: string;
    /**
     * Output only. The CampaignCriterion affected by this change.
     *
     * @generated from protobuf field: optional string campaign_criterion = 27;
     */
    campaignCriterion?: string;
    /**
     * Output only. The Feed affected by this change.
     *
     * @generated from protobuf field: optional string feed = 28;
     */
    feed?: string;
    /**
     * Output only. The FeedItem affected by this change.
     *
     * @generated from protobuf field: optional string feed_item = 29;
     */
    feedItem?: string;
    /**
     * Output only. The AdGroupFeed affected by this change.
     *
     * @generated from protobuf field: optional string ad_group_feed = 30;
     */
    adGroupFeed?: string;
    /**
     * Output only. The CampaignFeed affected by this change.
     *
     * @generated from protobuf field: optional string campaign_feed = 31;
     */
    campaignFeed?: string;
    /**
     * Output only. The AdGroupBidModifier affected by this change.
     *
     * @generated from protobuf field: optional string ad_group_bid_modifier = 32;
     */
    adGroupBidModifier?: string;
    /**
     * Output only. The SharedSet affected by this change.
     *
     * @generated from protobuf field: string shared_set = 33;
     */
    sharedSet: string;
    /**
     * Output only. The CampaignSharedSet affected by this change.
     *
     * @generated from protobuf field: string campaign_shared_set = 34;
     */
    campaignSharedSet: string;
    /**
     * Output only. The Asset affected by this change.
     *
     * @generated from protobuf field: string asset = 35;
     */
    asset: string;
    /**
     * Output only. The CustomerAsset affected by this change.
     *
     * @generated from protobuf field: string customer_asset = 36;
     */
    customerAsset: string;
    /**
     * Output only. The CampaignAsset affected by this change.
     *
     * @generated from protobuf field: string campaign_asset = 37;
     */
    campaignAsset: string;
    /**
     * Output only. The AdGroupAsset affected by this change.
     *
     * @generated from protobuf field: string ad_group_asset = 38;
     */
    adGroupAsset: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ChangeStatus$Type extends MessageType<ChangeStatus> {
    constructor() {
        super("google.ads.googleads.v11.resources.ChangeStatus", [
            { no: 1, name: "resource_name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/ChangeStatus" } } },
            { no: 24, name: "last_change_date_time", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 4, name: "resource_type", kind: "enum", T: () => ["google.ads.googleads.v11.enums.ChangeStatusResourceTypeEnum.ChangeStatusResourceType", ChangeStatusResourceTypeEnum_ChangeStatusResourceType], options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 17, name: "campaign", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/Campaign" } } },
            { no: 18, name: "ad_group", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroup" } } },
            { no: 8, name: "resource_status", kind: "enum", T: () => ["google.ads.googleads.v11.enums.ChangeStatusOperationEnum.ChangeStatusOperation", ChangeStatusOperationEnum_ChangeStatusOperation], options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 25, name: "ad_group_ad", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupAd" } } },
            { no: 26, name: "ad_group_criterion", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupCriterion" } } },
            { no: 27, name: "campaign_criterion", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/CampaignCriterion" } } },
            { no: 28, name: "feed", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/Feed" } } },
            { no: 29, name: "feed_item", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/FeedItem" } } },
            { no: 30, name: "ad_group_feed", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupFeed" } } },
            { no: 31, name: "campaign_feed", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/CampaignFeed" } } },
            { no: 32, name: "ad_group_bid_modifier", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupBidModifier" } } },
            { no: 33, name: "shared_set", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/SharedSet" } } },
            { no: 34, name: "campaign_shared_set", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/CampaignSharedSet" } } },
            { no: 35, name: "asset", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/Asset" } } },
            { no: 36, name: "customer_asset", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/CustomerAsset" } } },
            { no: 37, name: "campaign_asset", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/CampaignAsset" } } },
            { no: 38, name: "ad_group_asset", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupAsset" } } }
        ], { "google.api.resource": { type: "googleads.googleapis.com/ChangeStatus", pattern: ["customers/{customer_id}/changeStatus/{change_status_id}"] } });
    }
    create(value?: PartialMessage<ChangeStatus>): ChangeStatus {
        const message = { resourceName: "", resourceType: 0, resourceStatus: 0, sharedSet: "", campaignSharedSet: "", asset: "", customerAsset: "", campaignAsset: "", adGroupAsset: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ChangeStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChangeStatus): ChangeStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string resource_name */ 1:
                    message.resourceName = reader.string();
                    break;
                case /* optional string last_change_date_time */ 24:
                    message.lastChangeDateTime = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.ChangeStatusResourceTypeEnum.ChangeStatusResourceType resource_type */ 4:
                    message.resourceType = reader.int32();
                    break;
                case /* optional string campaign */ 17:
                    message.campaign = reader.string();
                    break;
                case /* optional string ad_group */ 18:
                    message.adGroup = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.ChangeStatusOperationEnum.ChangeStatusOperation resource_status */ 8:
                    message.resourceStatus = reader.int32();
                    break;
                case /* optional string ad_group_ad */ 25:
                    message.adGroupAd = reader.string();
                    break;
                case /* optional string ad_group_criterion */ 26:
                    message.adGroupCriterion = reader.string();
                    break;
                case /* optional string campaign_criterion */ 27:
                    message.campaignCriterion = reader.string();
                    break;
                case /* optional string feed */ 28:
                    message.feed = reader.string();
                    break;
                case /* optional string feed_item */ 29:
                    message.feedItem = reader.string();
                    break;
                case /* optional string ad_group_feed */ 30:
                    message.adGroupFeed = reader.string();
                    break;
                case /* optional string campaign_feed */ 31:
                    message.campaignFeed = reader.string();
                    break;
                case /* optional string ad_group_bid_modifier */ 32:
                    message.adGroupBidModifier = reader.string();
                    break;
                case /* string shared_set */ 33:
                    message.sharedSet = reader.string();
                    break;
                case /* string campaign_shared_set */ 34:
                    message.campaignSharedSet = reader.string();
                    break;
                case /* string asset */ 35:
                    message.asset = reader.string();
                    break;
                case /* string customer_asset */ 36:
                    message.customerAsset = reader.string();
                    break;
                case /* string campaign_asset */ 37:
                    message.campaignAsset = reader.string();
                    break;
                case /* string ad_group_asset */ 38:
                    message.adGroupAsset = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChangeStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string resource_name = 1; */
        if (message.resourceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.resourceName);
        /* optional string last_change_date_time = 24; */
        if (message.lastChangeDateTime !== undefined)
            writer.tag(24, WireType.LengthDelimited).string(message.lastChangeDateTime);
        /* google.ads.googleads.v11.enums.ChangeStatusResourceTypeEnum.ChangeStatusResourceType resource_type = 4; */
        if (message.resourceType !== 0)
            writer.tag(4, WireType.Varint).int32(message.resourceType);
        /* optional string campaign = 17; */
        if (message.campaign !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.campaign);
        /* optional string ad_group = 18; */
        if (message.adGroup !== undefined)
            writer.tag(18, WireType.LengthDelimited).string(message.adGroup);
        /* google.ads.googleads.v11.enums.ChangeStatusOperationEnum.ChangeStatusOperation resource_status = 8; */
        if (message.resourceStatus !== 0)
            writer.tag(8, WireType.Varint).int32(message.resourceStatus);
        /* optional string ad_group_ad = 25; */
        if (message.adGroupAd !== undefined)
            writer.tag(25, WireType.LengthDelimited).string(message.adGroupAd);
        /* optional string ad_group_criterion = 26; */
        if (message.adGroupCriterion !== undefined)
            writer.tag(26, WireType.LengthDelimited).string(message.adGroupCriterion);
        /* optional string campaign_criterion = 27; */
        if (message.campaignCriterion !== undefined)
            writer.tag(27, WireType.LengthDelimited).string(message.campaignCriterion);
        /* optional string feed = 28; */
        if (message.feed !== undefined)
            writer.tag(28, WireType.LengthDelimited).string(message.feed);
        /* optional string feed_item = 29; */
        if (message.feedItem !== undefined)
            writer.tag(29, WireType.LengthDelimited).string(message.feedItem);
        /* optional string ad_group_feed = 30; */
        if (message.adGroupFeed !== undefined)
            writer.tag(30, WireType.LengthDelimited).string(message.adGroupFeed);
        /* optional string campaign_feed = 31; */
        if (message.campaignFeed !== undefined)
            writer.tag(31, WireType.LengthDelimited).string(message.campaignFeed);
        /* optional string ad_group_bid_modifier = 32; */
        if (message.adGroupBidModifier !== undefined)
            writer.tag(32, WireType.LengthDelimited).string(message.adGroupBidModifier);
        /* string shared_set = 33; */
        if (message.sharedSet !== "")
            writer.tag(33, WireType.LengthDelimited).string(message.sharedSet);
        /* string campaign_shared_set = 34; */
        if (message.campaignSharedSet !== "")
            writer.tag(34, WireType.LengthDelimited).string(message.campaignSharedSet);
        /* string asset = 35; */
        if (message.asset !== "")
            writer.tag(35, WireType.LengthDelimited).string(message.asset);
        /* string customer_asset = 36; */
        if (message.customerAsset !== "")
            writer.tag(36, WireType.LengthDelimited).string(message.customerAsset);
        /* string campaign_asset = 37; */
        if (message.campaignAsset !== "")
            writer.tag(37, WireType.LengthDelimited).string(message.campaignAsset);
        /* string ad_group_asset = 38; */
        if (message.adGroupAsset !== "")
            writer.tag(38, WireType.LengthDelimited).string(message.adGroupAsset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.resources.ChangeStatus
 */
export const ChangeStatus = new ChangeStatus$Type();
