// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/resources/conversion_goal_campaign_config.proto" (package "google.ads.googleads.v11.resources", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { GoalConfigLevelEnum_GoalConfigLevel } from "../enums/goal_config_level";
/**
 * Conversion goal settings for a Campaign.
 *
 * @generated from protobuf message google.ads.googleads.v11.resources.ConversionGoalCampaignConfig
 */
export interface ConversionGoalCampaignConfig {
    /**
     * Immutable. The resource name of the conversion goal campaign config.
     * Conversion goal campaign config resource names have the form:
     *
     * `customers/{customer_id}/conversionGoalCampaignConfigs/{campaign_id}`
     *
     * @generated from protobuf field: string resource_name = 1;
     */
    resourceName: string;
    /**
     * Immutable. The campaign with which this conversion goal campaign config is associated.
     *
     * @generated from protobuf field: string campaign = 2;
     */
    campaign: string;
    /**
     * The level of goal config the campaign is using.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.GoalConfigLevelEnum.GoalConfigLevel goal_config_level = 3;
     */
    goalConfigLevel: GoalConfigLevelEnum_GoalConfigLevel;
    /**
     * The custom conversion goal the campaign is using for optimization.
     *
     * @generated from protobuf field: string custom_conversion_goal = 4;
     */
    customConversionGoal: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ConversionGoalCampaignConfig$Type extends MessageType<ConversionGoalCampaignConfig> {
    constructor() {
        super("google.ads.googleads.v11.resources.ConversionGoalCampaignConfig", [
            { no: 1, name: "resource_name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["IMMUTABLE"], "google.api.resource_reference": { type: "googleads.googleapis.com/ConversionGoalCampaignConfig" } } },
            { no: 2, name: "campaign", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["IMMUTABLE"], "google.api.resource_reference": { type: "googleads.googleapis.com/Campaign" } } },
            { no: 3, name: "goal_config_level", kind: "enum", T: () => ["google.ads.googleads.v11.enums.GoalConfigLevelEnum.GoalConfigLevel", GoalConfigLevelEnum_GoalConfigLevel] },
            { no: 4, name: "custom_conversion_goal", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.resource_reference": { type: "googleads.googleapis.com/CustomConversionGoal" } } }
        ], { "google.api.resource": { type: "googleads.googleapis.com/ConversionGoalCampaignConfig", pattern: ["customers/{customer_id}/conversionGoalCampaignConfigs/{campaign_id}"] } });
    }
    create(value?: PartialMessage<ConversionGoalCampaignConfig>): ConversionGoalCampaignConfig {
        const message = { resourceName: "", campaign: "", goalConfigLevel: 0, customConversionGoal: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConversionGoalCampaignConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConversionGoalCampaignConfig): ConversionGoalCampaignConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string resource_name */ 1:
                    message.resourceName = reader.string();
                    break;
                case /* string campaign */ 2:
                    message.campaign = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.GoalConfigLevelEnum.GoalConfigLevel goal_config_level */ 3:
                    message.goalConfigLevel = reader.int32();
                    break;
                case /* string custom_conversion_goal */ 4:
                    message.customConversionGoal = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConversionGoalCampaignConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string resource_name = 1; */
        if (message.resourceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.resourceName);
        /* string campaign = 2; */
        if (message.campaign !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.campaign);
        /* google.ads.googleads.v11.enums.GoalConfigLevelEnum.GoalConfigLevel goal_config_level = 3; */
        if (message.goalConfigLevel !== 0)
            writer.tag(3, WireType.Varint).int32(message.goalConfigLevel);
        /* string custom_conversion_goal = 4; */
        if (message.customConversionGoal !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.customConversionGoal);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.resources.ConversionGoalCampaignConfig
 */
export const ConversionGoalCampaignConfig = new ConversionGoalCampaignConfig$Type();
