// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/resources/keyword_theme_constant.proto" (package "google.ads.googleads.v11.resources", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing the Smart Campaign keyword theme constant resource.

/**
 * A Smart Campaign keyword theme constant.
 *
 * @generated from protobuf message google.ads.googleads.v11.resources.KeywordThemeConstant
 */
export interface KeywordThemeConstant {
    /**
     * Output only. The resource name of the keyword theme constant.
     * Keyword theme constant resource names have the form:
     *
     * `keywordThemeConstants/{keyword_theme_id}~{sub_keyword_theme_id}`
     *
     * @generated from protobuf field: string resource_name = 1;
     */
    resourceName: string;
    /**
     * Output only. The ISO-3166 Alpha-2 country code of the constant, eg. "US".
     * To display and query matching purpose, the keyword theme needs to be
     * localized.
     *
     * @generated from protobuf field: optional string country_code = 2;
     */
    countryCode?: string;
    /**
     * Output only. The ISO-639-1 language code with 2 letters of the constant, eg. "en".
     * To display and query matching purpose, the keyword theme needs to be
     * localized.
     *
     * @generated from protobuf field: optional string language_code = 3;
     */
    languageCode?: string;
    /**
     * Output only. The display name of the keyword theme or sub keyword theme.
     *
     * @generated from protobuf field: optional string display_name = 4;
     */
    displayName?: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class KeywordThemeConstant$Type extends MessageType<KeywordThemeConstant> {
    constructor() {
        super("google.ads.googleads.v11.resources.KeywordThemeConstant", [
            { no: 1, name: "resource_name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"], "google.api.resource_reference": { type: "googleads.googleapis.com/KeywordThemeConstant" } } },
            { no: 2, name: "country_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 3, name: "language_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 4, name: "display_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } }
        ], { "google.api.resource": { type: "googleads.googleapis.com/KeywordThemeConstant", pattern: ["keywordThemeConstants/{express_category_id}~{express_sub_category_id}"] } });
    }
    create(value?: PartialMessage<KeywordThemeConstant>): KeywordThemeConstant {
        const message = { resourceName: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<KeywordThemeConstant>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: KeywordThemeConstant): KeywordThemeConstant {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string resource_name */ 1:
                    message.resourceName = reader.string();
                    break;
                case /* optional string country_code */ 2:
                    message.countryCode = reader.string();
                    break;
                case /* optional string language_code */ 3:
                    message.languageCode = reader.string();
                    break;
                case /* optional string display_name */ 4:
                    message.displayName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: KeywordThemeConstant, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string resource_name = 1; */
        if (message.resourceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.resourceName);
        /* optional string country_code = 2; */
        if (message.countryCode !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.countryCode);
        /* optional string language_code = 3; */
        if (message.languageCode !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.languageCode);
        /* optional string display_name = 4; */
        if (message.displayName !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.displayName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.resources.KeywordThemeConstant
 */
export const KeywordThemeConstant = new KeywordThemeConstant$Type();
