// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/resources/merchant_center_link.proto" (package "google.ads.googleads.v11.resources", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MerchantCenterLinkStatusEnum_MerchantCenterLinkStatus } from "../enums/merchant_center_link_status";
// Proto file describing the Merchant Center link resource.

/**
 * A data sharing connection, proposed or in use,
 * between a Google Ads Customer and a Merchant Center account.
 *
 * @generated from protobuf message google.ads.googleads.v11.resources.MerchantCenterLink
 */
export interface MerchantCenterLink {
    /**
     * Immutable. The resource name of the merchant center link.
     * Merchant center link resource names have the form:
     *
     * `customers/{customer_id}/merchantCenterLinks/{merchant_center_id}`
     *
     * @generated from protobuf field: string resource_name = 1;
     */
    resourceName: string;
    /**
     * Output only. The ID of the Merchant Center account.
     * This field is readonly.
     *
     * @generated from protobuf field: optional int64 id = 6;
     */
    id?: bigint;
    /**
     * Output only. The name of the Merchant Center account.
     * This field is readonly.
     *
     * @generated from protobuf field: optional string merchant_center_account_name = 7;
     */
    merchantCenterAccountName?: string;
    /**
     * The status of the link.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.MerchantCenterLinkStatusEnum.MerchantCenterLinkStatus status = 5;
     */
    status: MerchantCenterLinkStatusEnum_MerchantCenterLinkStatus;
}
// @generated message type with reflection information, may provide speed optimized methods
class MerchantCenterLink$Type extends MessageType<MerchantCenterLink> {
    constructor() {
        super("google.ads.googleads.v11.resources.MerchantCenterLink", [
            { no: 1, name: "resource_name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["IMMUTABLE"], "google.api.resource_reference": { type: "googleads.googleapis.com/MerchantCenterLink" } } },
            { no: 6, name: "id", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 7, name: "merchant_center_account_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["OUTPUT_ONLY"] } },
            { no: 5, name: "status", kind: "enum", T: () => ["google.ads.googleads.v11.enums.MerchantCenterLinkStatusEnum.MerchantCenterLinkStatus", MerchantCenterLinkStatusEnum_MerchantCenterLinkStatus] }
        ], { "google.api.resource": { type: "googleads.googleapis.com/MerchantCenterLink", pattern: ["customers/{customer_id}/merchantCenterLinks/{merchant_center_id}"] } });
    }
    create(value?: PartialMessage<MerchantCenterLink>): MerchantCenterLink {
        const message = { resourceName: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<MerchantCenterLink>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MerchantCenterLink): MerchantCenterLink {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string resource_name */ 1:
                    message.resourceName = reader.string();
                    break;
                case /* optional int64 id */ 6:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* optional string merchant_center_account_name */ 7:
                    message.merchantCenterAccountName = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.MerchantCenterLinkStatusEnum.MerchantCenterLinkStatus status */ 5:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MerchantCenterLink, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string resource_name = 1; */
        if (message.resourceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.resourceName);
        /* optional int64 id = 6; */
        if (message.id !== undefined)
            writer.tag(6, WireType.Varint).int64(message.id);
        /* optional string merchant_center_account_name = 7; */
        if (message.merchantCenterAccountName !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.merchantCenterAccountName);
        /* google.ads.googleads.v11.enums.MerchantCenterLinkStatusEnum.MerchantCenterLinkStatus status = 5; */
        if (message.status !== 0)
            writer.tag(5, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.resources.MerchantCenterLink
 */
export const MerchantCenterLink = new MerchantCenterLink$Type();
