// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/services/ad_group_ad_service.proto" (package "google.ads.googleads.v11.services", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Status } from "../../google/rpc/status";
import { AdGroupAd } from "../resources/ad_group_ad";
import { PolicyValidationParameter } from "../common/policy";
import { FieldMask } from "../../google/protobuf/field_mask";
import { ResponseContentTypeEnum_ResponseContentType } from "../enums/response_content_type";
/**
 * Request message for [AdGroupAdService.MutateAdGroupAds][google.ads.googleads.v11.services.AdGroupAdService.MutateAdGroupAds].
 *
 * @generated from protobuf message google.ads.googleads.v11.services.MutateAdGroupAdsRequest
 */
export interface MutateAdGroupAdsRequest {
    /**
     * Required. The ID of the customer whose ads are being modified.
     *
     * @generated from protobuf field: string customer_id = 1;
     */
    customerId: string;
    /**
     * Required. The list of operations to perform on individual ads.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.services.AdGroupAdOperation operations = 2;
     */
    operations: AdGroupAdOperation[];
    /**
     * If true, successful operations will be carried out and invalid
     * operations will return errors. If false, all operations will be carried
     * out in one transaction if and only if they are all valid.
     * Default is false.
     *
     * @generated from protobuf field: bool partial_failure = 3;
     */
    partialFailure: boolean;
    /**
     * If true, the request is validated but not executed. Only errors are
     * returned, not results.
     *
     * @generated from protobuf field: bool validate_only = 4;
     */
    validateOnly: boolean;
    /**
     * The response content type setting. Determines whether the mutable resource
     * or just the resource name should be returned post mutation.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.ResponseContentTypeEnum.ResponseContentType response_content_type = 5;
     */
    responseContentType: ResponseContentTypeEnum_ResponseContentType;
}
/**
 * A single operation (create, update, remove) on an ad group ad.
 *
 * @generated from protobuf message google.ads.googleads.v11.services.AdGroupAdOperation
 */
export interface AdGroupAdOperation {
    /**
     * FieldMask that determines which resource fields are modified in an update.
     *
     * @generated from protobuf field: google.protobuf.FieldMask update_mask = 4;
     */
    updateMask?: FieldMask;
    /**
     * Configuration for how policies are validated.
     *
     * @generated from protobuf field: google.ads.googleads.v11.common.PolicyValidationParameter policy_validation_parameter = 5;
     */
    policyValidationParameter?: PolicyValidationParameter;
    /**
     * @generated from protobuf oneof: operation
     */
    operation: {
        oneofKind: "create";
        /**
         * Create operation: No resource name is expected for the new ad.
         *
         * @generated from protobuf field: google.ads.googleads.v11.resources.AdGroupAd create = 1;
         */
        create: AdGroupAd;
    } | {
        oneofKind: "update";
        /**
         * Update operation: The ad is expected to have a valid resource name.
         *
         * @generated from protobuf field: google.ads.googleads.v11.resources.AdGroupAd update = 2;
         */
        update: AdGroupAd;
    } | {
        oneofKind: "remove";
        /**
         * Remove operation: A resource name for the removed ad is expected,
         * in this format:
         *
         * `customers/{customer_id}/adGroupAds/{ad_group_id}~{ad_id}`
         *
         * @generated from protobuf field: string remove = 3;
         */
        remove: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Response message for an ad group ad mutate.
 *
 * @generated from protobuf message google.ads.googleads.v11.services.MutateAdGroupAdsResponse
 */
export interface MutateAdGroupAdsResponse {
    /**
     * Errors that pertain to operation failures in the partial failure mode.
     * Returned only when partial_failure = true and all errors occur inside the
     * operations. If any errors occur outside the operations (for example, auth
     * errors), we return an RPC level error.
     *
     * @generated from protobuf field: google.rpc.Status partial_failure_error = 3;
     */
    partialFailureError?: Status;
    /**
     * All results for the mutate.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.services.MutateAdGroupAdResult results = 2;
     */
    results: MutateAdGroupAdResult[];
}
/**
 * The result for the ad mutate.
 *
 * @generated from protobuf message google.ads.googleads.v11.services.MutateAdGroupAdResult
 */
export interface MutateAdGroupAdResult {
    /**
     * The resource name returned for successful operations.
     *
     * @generated from protobuf field: string resource_name = 1;
     */
    resourceName: string;
    /**
     * The mutated ad group ad with only mutable fields after mutate. The field
     * will only be returned when response_content_type is set to
     * "MUTABLE_RESOURCE".
     *
     * @generated from protobuf field: google.ads.googleads.v11.resources.AdGroupAd ad_group_ad = 2;
     */
    adGroupAd?: AdGroupAd;
}
// @generated message type with reflection information, may provide speed optimized methods
class MutateAdGroupAdsRequest$Type extends MessageType<MutateAdGroupAdsRequest> {
    constructor() {
        super("google.ads.googleads.v11.services.MutateAdGroupAdsRequest", [
            { no: 1, name: "customer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["REQUIRED"] } },
            { no: 2, name: "operations", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AdGroupAdOperation, options: { "google.api.field_behavior": ["REQUIRED"] } },
            { no: 3, name: "partial_failure", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "validate_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "response_content_type", kind: "enum", T: () => ["google.ads.googleads.v11.enums.ResponseContentTypeEnum.ResponseContentType", ResponseContentTypeEnum_ResponseContentType] }
        ]);
    }
    create(value?: PartialMessage<MutateAdGroupAdsRequest>): MutateAdGroupAdsRequest {
        const message = { customerId: "", operations: [], partialFailure: false, validateOnly: false, responseContentType: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<MutateAdGroupAdsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MutateAdGroupAdsRequest): MutateAdGroupAdsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string customer_id */ 1:
                    message.customerId = reader.string();
                    break;
                case /* repeated google.ads.googleads.v11.services.AdGroupAdOperation operations */ 2:
                    message.operations.push(AdGroupAdOperation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool partial_failure */ 3:
                    message.partialFailure = reader.bool();
                    break;
                case /* bool validate_only */ 4:
                    message.validateOnly = reader.bool();
                    break;
                case /* google.ads.googleads.v11.enums.ResponseContentTypeEnum.ResponseContentType response_content_type */ 5:
                    message.responseContentType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MutateAdGroupAdsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string customer_id = 1; */
        if (message.customerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.customerId);
        /* repeated google.ads.googleads.v11.services.AdGroupAdOperation operations = 2; */
        for (let i = 0; i < message.operations.length; i++)
            AdGroupAdOperation.internalBinaryWrite(message.operations[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool partial_failure = 3; */
        if (message.partialFailure !== false)
            writer.tag(3, WireType.Varint).bool(message.partialFailure);
        /* bool validate_only = 4; */
        if (message.validateOnly !== false)
            writer.tag(4, WireType.Varint).bool(message.validateOnly);
        /* google.ads.googleads.v11.enums.ResponseContentTypeEnum.ResponseContentType response_content_type = 5; */
        if (message.responseContentType !== 0)
            writer.tag(5, WireType.Varint).int32(message.responseContentType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.services.MutateAdGroupAdsRequest
 */
export const MutateAdGroupAdsRequest = new MutateAdGroupAdsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AdGroupAdOperation$Type extends MessageType<AdGroupAdOperation> {
    constructor() {
        super("google.ads.googleads.v11.services.AdGroupAdOperation", [
            { no: 4, name: "update_mask", kind: "message", T: () => FieldMask },
            { no: 5, name: "policy_validation_parameter", kind: "message", T: () => PolicyValidationParameter },
            { no: 1, name: "create", kind: "message", oneof: "operation", T: () => AdGroupAd },
            { no: 2, name: "update", kind: "message", oneof: "operation", T: () => AdGroupAd },
            { no: 3, name: "remove", kind: "scalar", oneof: "operation", T: 9 /*ScalarType.STRING*/, options: { "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupAd" } } }
        ]);
    }
    create(value?: PartialMessage<AdGroupAdOperation>): AdGroupAdOperation {
        const message = { operation: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AdGroupAdOperation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdGroupAdOperation): AdGroupAdOperation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.FieldMask update_mask */ 4:
                    message.updateMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.updateMask);
                    break;
                case /* google.ads.googleads.v11.common.PolicyValidationParameter policy_validation_parameter */ 5:
                    message.policyValidationParameter = PolicyValidationParameter.internalBinaryRead(reader, reader.uint32(), options, message.policyValidationParameter);
                    break;
                case /* google.ads.googleads.v11.resources.AdGroupAd create */ 1:
                    message.operation = {
                        oneofKind: "create",
                        create: AdGroupAd.internalBinaryRead(reader, reader.uint32(), options, (message.operation as any).create)
                    };
                    break;
                case /* google.ads.googleads.v11.resources.AdGroupAd update */ 2:
                    message.operation = {
                        oneofKind: "update",
                        update: AdGroupAd.internalBinaryRead(reader, reader.uint32(), options, (message.operation as any).update)
                    };
                    break;
                case /* string remove */ 3:
                    message.operation = {
                        oneofKind: "remove",
                        remove: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AdGroupAdOperation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.FieldMask update_mask = 4; */
        if (message.updateMask)
            FieldMask.internalBinaryWrite(message.updateMask, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.ads.googleads.v11.common.PolicyValidationParameter policy_validation_parameter = 5; */
        if (message.policyValidationParameter)
            PolicyValidationParameter.internalBinaryWrite(message.policyValidationParameter, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.ads.googleads.v11.resources.AdGroupAd create = 1; */
        if (message.operation.oneofKind === "create")
            AdGroupAd.internalBinaryWrite(message.operation.create, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.ads.googleads.v11.resources.AdGroupAd update = 2; */
        if (message.operation.oneofKind === "update")
            AdGroupAd.internalBinaryWrite(message.operation.update, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string remove = 3; */
        if (message.operation.oneofKind === "remove")
            writer.tag(3, WireType.LengthDelimited).string(message.operation.remove);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.services.AdGroupAdOperation
 */
export const AdGroupAdOperation = new AdGroupAdOperation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MutateAdGroupAdsResponse$Type extends MessageType<MutateAdGroupAdsResponse> {
    constructor() {
        super("google.ads.googleads.v11.services.MutateAdGroupAdsResponse", [
            { no: 3, name: "partial_failure_error", kind: "message", T: () => Status },
            { no: 2, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MutateAdGroupAdResult }
        ]);
    }
    create(value?: PartialMessage<MutateAdGroupAdsResponse>): MutateAdGroupAdsResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<MutateAdGroupAdsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MutateAdGroupAdsResponse): MutateAdGroupAdsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.rpc.Status partial_failure_error */ 3:
                    message.partialFailureError = Status.internalBinaryRead(reader, reader.uint32(), options, message.partialFailureError);
                    break;
                case /* repeated google.ads.googleads.v11.services.MutateAdGroupAdResult results */ 2:
                    message.results.push(MutateAdGroupAdResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MutateAdGroupAdsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.rpc.Status partial_failure_error = 3; */
        if (message.partialFailureError)
            Status.internalBinaryWrite(message.partialFailureError, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated google.ads.googleads.v11.services.MutateAdGroupAdResult results = 2; */
        for (let i = 0; i < message.results.length; i++)
            MutateAdGroupAdResult.internalBinaryWrite(message.results[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.services.MutateAdGroupAdsResponse
 */
export const MutateAdGroupAdsResponse = new MutateAdGroupAdsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MutateAdGroupAdResult$Type extends MessageType<MutateAdGroupAdResult> {
    constructor() {
        super("google.ads.googleads.v11.services.MutateAdGroupAdResult", [
            { no: 1, name: "resource_name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.resource_reference": { type: "googleads.googleapis.com/AdGroupAd" } } },
            { no: 2, name: "ad_group_ad", kind: "message", T: () => AdGroupAd }
        ]);
    }
    create(value?: PartialMessage<MutateAdGroupAdResult>): MutateAdGroupAdResult {
        const message = { resourceName: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<MutateAdGroupAdResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MutateAdGroupAdResult): MutateAdGroupAdResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string resource_name */ 1:
                    message.resourceName = reader.string();
                    break;
                case /* google.ads.googleads.v11.resources.AdGroupAd ad_group_ad */ 2:
                    message.adGroupAd = AdGroupAd.internalBinaryRead(reader, reader.uint32(), options, message.adGroupAd);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MutateAdGroupAdResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string resource_name = 1; */
        if (message.resourceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.resourceName);
        /* google.ads.googleads.v11.resources.AdGroupAd ad_group_ad = 2; */
        if (message.adGroupAd)
            AdGroupAd.internalBinaryWrite(message.adGroupAd, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.services.MutateAdGroupAdResult
 */
export const MutateAdGroupAdResult = new MutateAdGroupAdResult$Type();
/**
 * @generated ServiceType for protobuf service google.ads.googleads.v11.services.AdGroupAdService
 */
export const AdGroupAdService = new ServiceType("google.ads.googleads.v11.services.AdGroupAdService", [
    { name: "MutateAdGroupAds", options: { "google.api.http": { post: "/v11/customers/{customer_id=*}/adGroupAds:mutate", body: "*" }, "google.api.method_signature": ["customer_id,operations"] }, I: MutateAdGroupAdsRequest, O: MutateAdGroupAdsResponse }
], { "google.api.default_host": "googleads.googleapis.com", "google.api.oauth_scopes": "https://www.googleapis.com/auth/adwords" });
