// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/services/customer_service.proto" (package "google.ads.googleads.v11.services", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CustomerService } from "./customer_service";
import type { CreateCustomerClientResponse } from "./customer_service";
import type { CreateCustomerClientRequest } from "./customer_service";
import type { ListAccessibleCustomersResponse } from "./customer_service";
import type { ListAccessibleCustomersRequest } from "./customer_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { MutateCustomerResponse } from "./customer_service";
import type { MutateCustomerRequest } from "./customer_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// Proto file describing the Customer service.

/**
 * Service to manage customers.
 *
 * @generated from protobuf service google.ads.googleads.v11.services.CustomerService
 */
export interface ICustomerServiceClient {
    /**
     * Updates a customer. Operation statuses are returned.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [DatabaseError]()
     *   [FieldMaskError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [QuotaError]()
     *   [RequestError]()
     *   [UrlFieldError]()
     *
     * @generated from protobuf rpc: MutateCustomer(google.ads.googleads.v11.services.MutateCustomerRequest) returns (google.ads.googleads.v11.services.MutateCustomerResponse);
     */
    mutateCustomer(input: MutateCustomerRequest, options?: RpcOptions): UnaryCall<MutateCustomerRequest, MutateCustomerResponse>;
    /**
     * Returns resource names of customers directly accessible by the
     * user authenticating the call.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [QuotaError]()
     *   [RequestError]()
     *
     * @generated from protobuf rpc: ListAccessibleCustomers(google.ads.googleads.v11.services.ListAccessibleCustomersRequest) returns (google.ads.googleads.v11.services.ListAccessibleCustomersResponse);
     */
    listAccessibleCustomers(input: ListAccessibleCustomersRequest, options?: RpcOptions): UnaryCall<ListAccessibleCustomersRequest, ListAccessibleCustomersResponse>;
    /**
     * Creates a new client under manager. The new client customer is returned.
     *
     * List of thrown errors:
     *   [AccessInvitationError]()
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [CurrencyCodeError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [ManagerLinkError]()
     *   [QuotaError]()
     *   [RequestError]()
     *   [StringLengthError]()
     *   [TimeZoneError]()
     *
     * @generated from protobuf rpc: CreateCustomerClient(google.ads.googleads.v11.services.CreateCustomerClientRequest) returns (google.ads.googleads.v11.services.CreateCustomerClientResponse);
     */
    createCustomerClient(input: CreateCustomerClientRequest, options?: RpcOptions): UnaryCall<CreateCustomerClientRequest, CreateCustomerClientResponse>;
}
// Proto file describing the Customer service.

/**
 * Service to manage customers.
 *
 * @generated from protobuf service google.ads.googleads.v11.services.CustomerService
 */
export class CustomerServiceClient implements ICustomerServiceClient, ServiceInfo {
    typeName = CustomerService.typeName;
    methods = CustomerService.methods;
    options = CustomerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Updates a customer. Operation statuses are returned.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [DatabaseError]()
     *   [FieldMaskError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [QuotaError]()
     *   [RequestError]()
     *   [UrlFieldError]()
     *
     * @generated from protobuf rpc: MutateCustomer(google.ads.googleads.v11.services.MutateCustomerRequest) returns (google.ads.googleads.v11.services.MutateCustomerResponse);
     */
    mutateCustomer(input: MutateCustomerRequest, options?: RpcOptions): UnaryCall<MutateCustomerRequest, MutateCustomerResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MutateCustomerRequest, MutateCustomerResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Returns resource names of customers directly accessible by the
     * user authenticating the call.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [QuotaError]()
     *   [RequestError]()
     *
     * @generated from protobuf rpc: ListAccessibleCustomers(google.ads.googleads.v11.services.ListAccessibleCustomersRequest) returns (google.ads.googleads.v11.services.ListAccessibleCustomersResponse);
     */
    listAccessibleCustomers(input: ListAccessibleCustomersRequest, options?: RpcOptions): UnaryCall<ListAccessibleCustomersRequest, ListAccessibleCustomersResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessibleCustomersRequest, ListAccessibleCustomersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Creates a new client under manager. The new client customer is returned.
     *
     * List of thrown errors:
     *   [AccessInvitationError]()
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [CurrencyCodeError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [ManagerLinkError]()
     *   [QuotaError]()
     *   [RequestError]()
     *   [StringLengthError]()
     *   [TimeZoneError]()
     *
     * @generated from protobuf rpc: CreateCustomerClient(google.ads.googleads.v11.services.CreateCustomerClientRequest) returns (google.ads.googleads.v11.services.CreateCustomerClientResponse);
     */
    createCustomerClient(input: CreateCustomerClientRequest, options?: RpcOptions): UnaryCall<CreateCustomerClientRequest, CreateCustomerClientResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCustomerClientRequest, CreateCustomerClientResponse>("unary", this._transport, method, opt, input);
    }
}
