// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/services/invoice_service.proto" (package "google.ads.googleads.v11.services", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { InvoiceService } from "./invoice_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListInvoicesResponse } from "./invoice_service";
import type { ListInvoicesRequest } from "./invoice_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// Proto file describing the Invoice service.

/**
 * A service to fetch invoices issued for a billing setup during a given month.
 *
 * @generated from protobuf service google.ads.googleads.v11.services.InvoiceService
 */
export interface IInvoiceServiceClient {
    /**
     * Returns all invoices associated with a billing setup, for a given month.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [FieldError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [InvoiceError]()
     *   [QuotaError]()
     *   [RequestError]()
     *
     * @generated from protobuf rpc: ListInvoices(google.ads.googleads.v11.services.ListInvoicesRequest) returns (google.ads.googleads.v11.services.ListInvoicesResponse);
     */
    listInvoices(input: ListInvoicesRequest, options?: RpcOptions): UnaryCall<ListInvoicesRequest, ListInvoicesResponse>;
}
// Proto file describing the Invoice service.

/**
 * A service to fetch invoices issued for a billing setup during a given month.
 *
 * @generated from protobuf service google.ads.googleads.v11.services.InvoiceService
 */
export class InvoiceServiceClient implements IInvoiceServiceClient, ServiceInfo {
    typeName = InvoiceService.typeName;
    methods = InvoiceService.methods;
    options = InvoiceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns all invoices associated with a billing setup, for a given month.
     *
     * List of thrown errors:
     *   [AuthenticationError]()
     *   [AuthorizationError]()
     *   [FieldError]()
     *   [HeaderError]()
     *   [InternalError]()
     *   [InvoiceError]()
     *   [QuotaError]()
     *   [RequestError]()
     *
     * @generated from protobuf rpc: ListInvoices(google.ads.googleads.v11.services.ListInvoicesRequest) returns (google.ads.googleads.v11.services.ListInvoicesResponse);
     */
    listInvoices(input: ListInvoicesRequest, options?: RpcOptions): UnaryCall<ListInvoicesRequest, ListInvoicesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListInvoicesRequest, ListInvoicesResponse>("unary", this._transport, method, opt, input);
    }
}
