// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/account_link_status.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Container for enum describing possible statuses of an account link.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.AccountLinkStatusEnum
 */
export interface AccountLinkStatusEnum {
}
/**
 * Describes the possible statuses for a link between a Google Ads customer
 * and another account.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.AccountLinkStatusEnum.AccountLinkStatus
 */
export enum AccountLinkStatusEnum_AccountLinkStatus {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * The link is enabled.
     *
     * @generated from protobuf enum value: ENABLED = 2;
     */
    ENABLED = 2,
    /**
     * The link is removed/disabled.
     *
     * @generated from protobuf enum value: REMOVED = 3;
     */
    REMOVED = 3,
    /**
     * The link to the other account has been requested. A user on the other
     * account may now approve the link by setting the status to ENABLED.
     *
     * @generated from protobuf enum value: REQUESTED = 4;
     */
    REQUESTED = 4,
    /**
     * This link has been requested by a user on the other account. It may be
     * approved by a user on this account by setting the status to ENABLED.
     *
     * @generated from protobuf enum value: PENDING_APPROVAL = 5;
     */
    PENDING_APPROVAL = 5,
    /**
     * The link is rejected by the approver.
     *
     * @generated from protobuf enum value: REJECTED = 6;
     */
    REJECTED = 6,
    /**
     * The link is revoked by the user who requested the link.
     *
     * @generated from protobuf enum value: REVOKED = 7;
     */
    REVOKED = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class AccountLinkStatusEnum$Type extends MessageType<AccountLinkStatusEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.AccountLinkStatusEnum", []);
    }
    create(value?: PartialMessage<AccountLinkStatusEnum>): AccountLinkStatusEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AccountLinkStatusEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountLinkStatusEnum): AccountLinkStatusEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: AccountLinkStatusEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.AccountLinkStatusEnum
 */
export const AccountLinkStatusEnum = new AccountLinkStatusEnum$Type();
