// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/audience_insights_dimension.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing a plannable network.

/**
 * Container for enum describing audience insights dimensions.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.AudienceInsightsDimensionEnum
 */
export interface AudienceInsightsDimensionEnum {
}
/**
 * Possible audience dimensions for use in generating insights.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.AudienceInsightsDimensionEnum.AudienceInsightsDimension
 */
export enum AudienceInsightsDimensionEnum_AudienceInsightsDimension {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The value is unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * A Product & Service category.
     *
     * @generated from protobuf enum value: CATEGORY = 2;
     */
    CATEGORY = 2,
    /**
     * A Knowledge Graph entity.
     *
     * @generated from protobuf enum value: KNOWLEDGE_GRAPH = 3;
     */
    KNOWLEDGE_GRAPH = 3,
    /**
     * A country, represented by a geo target.
     *
     * @generated from protobuf enum value: GEO_TARGET_COUNTRY = 4;
     */
    GEO_TARGET_COUNTRY = 4,
    /**
     * A geographic location within a country.
     *
     * @generated from protobuf enum value: SUB_COUNTRY_LOCATION = 5;
     */
    SUB_COUNTRY_LOCATION = 5,
    /**
     * A YouTube channel.
     *
     * @generated from protobuf enum value: YOUTUBE_CHANNEL = 6;
     */
    YOUTUBE_CHANNEL = 6,
    /**
     * A YouTube Dynamic Lineup.
     *
     * @generated from protobuf enum value: YOUTUBE_DYNAMIC_LINEUP = 7;
     */
    YOUTUBE_DYNAMIC_LINEUP = 7,
    /**
     * An Affinity UserInterest.
     *
     * @generated from protobuf enum value: AFFINITY_USER_INTEREST = 8;
     */
    AFFINITY_USER_INTEREST = 8,
    /**
     * An In-Market UserInterest.
     *
     * @generated from protobuf enum value: IN_MARKET_USER_INTEREST = 9;
     */
    IN_MARKET_USER_INTEREST = 9,
    /**
     * A Parental Status value (parent, or not a parent).
     *
     * @generated from protobuf enum value: PARENTAL_STATUS = 10;
     */
    PARENTAL_STATUS = 10,
    /**
     * A household income percentile range.
     *
     * @generated from protobuf enum value: INCOME_RANGE = 11;
     */
    INCOME_RANGE = 11,
    /**
     * An age range.
     *
     * @generated from protobuf enum value: AGE_RANGE = 12;
     */
    AGE_RANGE = 12,
    /**
     * A gender.
     *
     * @generated from protobuf enum value: GENDER = 13;
     */
    GENDER = 13
}
// @generated message type with reflection information, may provide speed optimized methods
class AudienceInsightsDimensionEnum$Type extends MessageType<AudienceInsightsDimensionEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.AudienceInsightsDimensionEnum", []);
    }
    create(value?: PartialMessage<AudienceInsightsDimensionEnum>): AudienceInsightsDimensionEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AudienceInsightsDimensionEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AudienceInsightsDimensionEnum): AudienceInsightsDimensionEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: AudienceInsightsDimensionEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.AudienceInsightsDimensionEnum
 */
export const AudienceInsightsDimensionEnum = new AudienceInsightsDimensionEnum$Type();
