// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/bidding_strategy_type.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing bidding schemes.

/**
 * Container for enum describing possible bidding strategy types.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.BiddingStrategyTypeEnum
 */
export interface BiddingStrategyTypeEnum {
}
/**
 * Enum describing possible bidding strategy types.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.BiddingStrategyTypeEnum.BiddingStrategyType
 */
export enum BiddingStrategyTypeEnum_BiddingStrategyType {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Commission is an automatic bidding strategy in which the advertiser pays
     * a certain portion of the conversion value.
     *
     * @generated from protobuf enum value: COMMISSION = 16;
     */
    COMMISSION = 16,
    /**
     * Enhanced CPC is a bidding strategy that raises bids for clicks
     * that seem more likely to lead to a conversion and lowers
     * them for clicks where they seem less likely.
     *
     * @generated from protobuf enum value: ENHANCED_CPC = 2;
     */
    ENHANCED_CPC = 2,
    /**
     * Used for return value only. Indicates that a campaign does not have a
     * bidding strategy. This prevents the campaign from serving. For example,
     * a campaign may be attached to a manager bidding strategy and the serving
     * account is subsequently unlinked from the manager account. In this case
     * the campaign will automatically be detached from the now inaccessible
     * manager bidding strategy and transition to the INVALID bidding strategy
     * type.
     *
     * @generated from protobuf enum value: INVALID = 17;
     */
    INVALID = 17,
    /**
     * Manual bidding strategy that allows advertiser to set the bid per
     * advertiser-specified action.
     *
     * @generated from protobuf enum value: MANUAL_CPA = 18;
     */
    MANUAL_CPA = 18,
    /**
     * Manual click based bidding where user pays per click.
     *
     * @generated from protobuf enum value: MANUAL_CPC = 3;
     */
    MANUAL_CPC = 3,
    /**
     * Manual impression based bidding
     * where user pays per thousand impressions.
     *
     * @generated from protobuf enum value: MANUAL_CPM = 4;
     */
    MANUAL_CPM = 4,
    /**
     * A bidding strategy that pays a configurable amount per video view.
     *
     * @generated from protobuf enum value: MANUAL_CPV = 13;
     */
    MANUAL_CPV = 13,
    /**
     * A bidding strategy that automatically maximizes number of conversions
     * given a daily budget.
     *
     * @generated from protobuf enum value: MAXIMIZE_CONVERSIONS = 10;
     */
    MAXIMIZE_CONVERSIONS = 10,
    /**
     * An automated bidding strategy that automatically sets bids to maximize
     * revenue while spending your budget.
     *
     * @generated from protobuf enum value: MAXIMIZE_CONVERSION_VALUE = 11;
     */
    MAXIMIZE_CONVERSION_VALUE = 11,
    /**
     * Page-One Promoted bidding scheme, which sets max cpc bids to
     * target impressions on page one or page one promoted slots on google.com.
     * This enum value is deprecated.
     *
     * @generated from protobuf enum value: PAGE_ONE_PROMOTED = 5;
     */
    PAGE_ONE_PROMOTED = 5,
    /**
     * Percent Cpc is bidding strategy where bids are a fraction of the
     * advertised price for some good or service.
     *
     * @generated from protobuf enum value: PERCENT_CPC = 12;
     */
    PERCENT_CPC = 12,
    /**
     * Target CPA is an automated bid strategy that sets bids
     * to help get as many conversions as possible
     * at the target cost-per-acquisition (CPA) you set.
     *
     * @generated from protobuf enum value: TARGET_CPA = 6;
     */
    TARGET_CPA = 6,
    /**
     * Target CPM is an automated bid strategy that sets bids to help get
     * as many impressions as possible at the target cost per one thousand
     * impressions (CPM) you set.
     *
     * @generated from protobuf enum value: TARGET_CPM = 14;
     */
    TARGET_CPM = 14,
    /**
     * An automated bidding strategy that sets bids so that a certain percentage
     * of search ads are shown at the top of the first page (or other targeted
     * location).
     *
     * @generated from protobuf enum value: TARGET_IMPRESSION_SHARE = 15;
     */
    TARGET_IMPRESSION_SHARE = 15,
    /**
     * Target Outrank Share is an automated bidding strategy that sets bids
     * based on the target fraction of auctions where the advertiser
     * should outrank a specific competitor.
     * This enum value is deprecated.
     *
     * @generated from protobuf enum value: TARGET_OUTRANK_SHARE = 7;
     */
    TARGET_OUTRANK_SHARE = 7,
    /**
     * Target ROAS is an automated bidding strategy
     * that helps you maximize revenue while averaging
     * a specific target Return On Average Spend (ROAS).
     *
     * @generated from protobuf enum value: TARGET_ROAS = 8;
     */
    TARGET_ROAS = 8,
    /**
     * Target Spend is an automated bid strategy that sets your bids
     * to help get as many clicks as possible within your budget.
     *
     * @generated from protobuf enum value: TARGET_SPEND = 9;
     */
    TARGET_SPEND = 9
}
// @generated message type with reflection information, may provide speed optimized methods
class BiddingStrategyTypeEnum$Type extends MessageType<BiddingStrategyTypeEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.BiddingStrategyTypeEnum", []);
    }
    create(value?: PartialMessage<BiddingStrategyTypeEnum>): BiddingStrategyTypeEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BiddingStrategyTypeEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BiddingStrategyTypeEnum): BiddingStrategyTypeEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: BiddingStrategyTypeEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.BiddingStrategyTypeEnum
 */
export const BiddingStrategyTypeEnum = new BiddingStrategyTypeEnum$Type();
