// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/conversion_action_counting_type.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing conversion action counting type.

/**
 * Container for enum describing the conversion deduplication mode for
 * conversion optimizer.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.ConversionActionCountingTypeEnum
 */
export interface ConversionActionCountingTypeEnum {
}
/**
 * Indicates how conversions for this action will be counted. For more
 * information, see https://support.google.com/google-ads/answer/3438531.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.ConversionActionCountingTypeEnum.ConversionActionCountingType
 */
export enum ConversionActionCountingTypeEnum_ConversionActionCountingType {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Count only one conversion per click.
     *
     * @generated from protobuf enum value: ONE_PER_CLICK = 2;
     */
    ONE_PER_CLICK = 2,
    /**
     * Count all conversions per click.
     *
     * @generated from protobuf enum value: MANY_PER_CLICK = 3;
     */
    MANY_PER_CLICK = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ConversionActionCountingTypeEnum$Type extends MessageType<ConversionActionCountingTypeEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.ConversionActionCountingTypeEnum", []);
    }
    create(value?: PartialMessage<ConversionActionCountingTypeEnum>): ConversionActionCountingTypeEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConversionActionCountingTypeEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConversionActionCountingTypeEnum): ConversionActionCountingTypeEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ConversionActionCountingTypeEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.ConversionActionCountingTypeEnum
 */
export const ConversionActionCountingTypeEnum = new ConversionActionCountingTypeEnum$Type();
