// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/hotel_reconciliation_status.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing hotel reconciliation row status.

/**
 * Container for HotelReconciliationStatus.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.HotelReconciliationStatusEnum
 */
export interface HotelReconciliationStatusEnum {
}
/**
 * Status of the hotel booking reconciliation.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.HotelReconciliationStatusEnum.HotelReconciliationStatus
 */
export enum HotelReconciliationStatusEnum_HotelReconciliationStatus {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The value is unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Bookings are for a future date, or a stay is underway but the check-out
     * date hasn't passed. An active reservation can't be reconciled.
     *
     * @generated from protobuf enum value: RESERVATION_ENABLED = 2;
     */
    RESERVATION_ENABLED = 2,
    /**
     * Check-out has already taken place, or the booked dates have passed
     * without cancellation. Bookings that are not reconciled within 45 days of
     * the check-out date are billed based on the original booking price.
     *
     * @generated from protobuf enum value: RECONCILIATION_NEEDED = 3;
     */
    RECONCILIATION_NEEDED = 3,
    /**
     * These bookings have been reconciled. Reconciled bookings are billed 45
     * days after the check-out date.
     *
     * @generated from protobuf enum value: RECONCILED = 4;
     */
    RECONCILED = 4,
    /**
     * This booking was marked as canceled. Canceled stays with a value greater
     * than zero (due to minimum stay rules or cancellation fees) are billed 45
     * days after the check-out date.
     *
     * @generated from protobuf enum value: CANCELED = 5;
     */
    CANCELED = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class HotelReconciliationStatusEnum$Type extends MessageType<HotelReconciliationStatusEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.HotelReconciliationStatusEnum", []);
    }
    create(value?: PartialMessage<HotelReconciliationStatusEnum>): HotelReconciliationStatusEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HotelReconciliationStatusEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HotelReconciliationStatusEnum): HotelReconciliationStatusEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: HotelReconciliationStatusEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.HotelReconciliationStatusEnum
 */
export const HotelReconciliationStatusEnum = new HotelReconciliationStatusEnum$Type();
