// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/real_estate_placeholder_field.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing Real Estate placeholder fields.

/**
 * Values for Real Estate placeholder fields.
 * For more information about dynamic remarketing feeds, see
 * https://support.google.com/google-ads/answer/6053288.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.RealEstatePlaceholderFieldEnum
 */
export interface RealEstatePlaceholderFieldEnum {
}
/**
 * Possible values for Real Estate placeholder fields.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.RealEstatePlaceholderFieldEnum.RealEstatePlaceholderField
 */
export enum RealEstatePlaceholderFieldEnum_RealEstatePlaceholderField {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Data Type: STRING. Unique ID.
     *
     * @generated from protobuf enum value: LISTING_ID = 2;
     */
    LISTING_ID = 2,
    /**
     * Data Type: STRING. Main headline with listing name to be shown in dynamic
     * ad.
     *
     * @generated from protobuf enum value: LISTING_NAME = 3;
     */
    LISTING_NAME = 3,
    /**
     * Data Type: STRING. City name to be shown in dynamic ad.
     *
     * @generated from protobuf enum value: CITY_NAME = 4;
     */
    CITY_NAME = 4,
    /**
     * Data Type: STRING. Description of listing to be shown in dynamic ad.
     *
     * @generated from protobuf enum value: DESCRIPTION = 5;
     */
    DESCRIPTION = 5,
    /**
     * Data Type: STRING. Complete listing address, including postal code.
     *
     * @generated from protobuf enum value: ADDRESS = 6;
     */
    ADDRESS = 6,
    /**
     * Data Type: STRING. Price to be shown in the ad.
     * Example: "100.00 USD"
     *
     * @generated from protobuf enum value: PRICE = 7;
     */
    PRICE = 7,
    /**
     * Data Type: STRING. Formatted price to be shown in the ad.
     * Example: "Starting at $100.00 USD", "$80 - $100"
     *
     * @generated from protobuf enum value: FORMATTED_PRICE = 8;
     */
    FORMATTED_PRICE = 8,
    /**
     * Data Type: URL. Image to be displayed in the ad.
     *
     * @generated from protobuf enum value: IMAGE_URL = 9;
     */
    IMAGE_URL = 9,
    /**
     * Data Type: STRING. Type of property (house, condo, apartment, etc.) used
     * to group like items together for recommendation engine.
     *
     * @generated from protobuf enum value: PROPERTY_TYPE = 10;
     */
    PROPERTY_TYPE = 10,
    /**
     * Data Type: STRING. Type of listing (resale, rental, foreclosure, etc.)
     * used to group like items together for recommendation engine.
     *
     * @generated from protobuf enum value: LISTING_TYPE = 11;
     */
    LISTING_TYPE = 11,
    /**
     * Data Type: STRING_LIST. Keywords used for product retrieval.
     *
     * @generated from protobuf enum value: CONTEXTUAL_KEYWORDS = 12;
     */
    CONTEXTUAL_KEYWORDS = 12,
    /**
     * Data Type: URL_LIST. Final URLs to be used in ad when using Upgraded
     * URLs; the more specific the better (for example, the individual URL of a
     * specific listing and its location).
     *
     * @generated from protobuf enum value: FINAL_URLS = 13;
     */
    FINAL_URLS = 13,
    /**
     * Data Type: URL_LIST. Final mobile URLs for the ad when using Upgraded
     * URLs.
     *
     * @generated from protobuf enum value: FINAL_MOBILE_URLS = 14;
     */
    FINAL_MOBILE_URLS = 14,
    /**
     * Data Type: URL. Tracking template for the ad when using Upgraded URLs.
     *
     * @generated from protobuf enum value: TRACKING_URL = 15;
     */
    TRACKING_URL = 15,
    /**
     * Data Type: STRING. Android app link. Must be formatted as:
     * android-app://{package_id}/{scheme}/{host_path}.
     * The components are defined as follows:
     * package_id: app ID as specified in Google Play.
     * scheme: the scheme to pass to the application. Can be HTTP, or a custom
     *   scheme.
     * host_path: identifies the specific content within your application.
     *
     * @generated from protobuf enum value: ANDROID_APP_LINK = 16;
     */
    ANDROID_APP_LINK = 16,
    /**
     * Data Type: STRING_LIST. List of recommended listing IDs to show together
     * with this item.
     *
     * @generated from protobuf enum value: SIMILAR_LISTING_IDS = 17;
     */
    SIMILAR_LISTING_IDS = 17,
    /**
     * Data Type: STRING. iOS app link.
     *
     * @generated from protobuf enum value: IOS_APP_LINK = 18;
     */
    IOS_APP_LINK = 18,
    /**
     * Data Type: INT64. iOS app store ID.
     *
     * @generated from protobuf enum value: IOS_APP_STORE_ID = 19;
     */
    IOS_APP_STORE_ID = 19
}
// @generated message type with reflection information, may provide speed optimized methods
class RealEstatePlaceholderFieldEnum$Type extends MessageType<RealEstatePlaceholderFieldEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.RealEstatePlaceholderFieldEnum", []);
    }
    create(value?: PartialMessage<RealEstatePlaceholderFieldEnum>): RealEstatePlaceholderFieldEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RealEstatePlaceholderFieldEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RealEstatePlaceholderFieldEnum): RealEstatePlaceholderFieldEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RealEstatePlaceholderFieldEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.RealEstatePlaceholderFieldEnum
 */
export const RealEstatePlaceholderFieldEnum = new RealEstatePlaceholderFieldEnum$Type();
