// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/enums/value_rule_geo_location_match_type.proto" (package "google.ads.googleads.v11.enums", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing conversion value rule geo location match type.

/**
 * Container for enum describing possible geographic location matching types
 * used in a conversion value rule.
 *
 * @generated from protobuf message google.ads.googleads.v11.enums.ValueRuleGeoLocationMatchTypeEnum
 */
export interface ValueRuleGeoLocationMatchTypeEnum {
}
/**
 * Possible geographic location matching types.
 *
 * @generated from protobuf enum google.ads.googleads.v11.enums.ValueRuleGeoLocationMatchTypeEnum.ValueRuleGeoLocationMatchType
 */
export enum ValueRuleGeoLocationMatchTypeEnum_ValueRuleGeoLocationMatchType {
    /**
     * Not specified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Either Area of Interest or Location of Presence can be used to match.
     *
     * @generated from protobuf enum value: ANY = 2;
     */
    ANY = 2,
    /**
     * Only Location of Presence can be used to match.
     *
     * @generated from protobuf enum value: LOCATION_OF_PRESENCE = 3;
     */
    LOCATION_OF_PRESENCE = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ValueRuleGeoLocationMatchTypeEnum$Type extends MessageType<ValueRuleGeoLocationMatchTypeEnum> {
    constructor() {
        super("google.ads.googleads.v11.enums.ValueRuleGeoLocationMatchTypeEnum", []);
    }
    create(value?: PartialMessage<ValueRuleGeoLocationMatchTypeEnum>): ValueRuleGeoLocationMatchTypeEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ValueRuleGeoLocationMatchTypeEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValueRuleGeoLocationMatchTypeEnum): ValueRuleGeoLocationMatchTypeEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ValueRuleGeoLocationMatchTypeEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.enums.ValueRuleGeoLocationMatchTypeEnum
 */
export const ValueRuleGeoLocationMatchTypeEnum = new ValueRuleGeoLocationMatchTypeEnum$Type();
