// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/common/extensions.proto" (package "google.ads.googleads.v11.common", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PromotionExtensionOccasionEnum_PromotionExtensionOccasion } from "../enums/promotion_extension_occasion";
import { PromotionExtensionDiscountModifierEnum_PromotionExtensionDiscountModifier } from "../enums/promotion_extension_discount_modifier";
import { PriceExtensionPriceUnitEnum_PriceExtensionPriceUnit } from "../enums/price_extension_price_unit";
import { Money } from "./feed_common";
import { PriceExtensionPriceQualifierEnum_PriceExtensionPriceQualifier } from "../enums/price_extension_price_qualifier";
import { PriceExtensionTypeEnum_PriceExtensionType } from "../enums/price_extension_type";
import { CallConversionReportingStateEnum_CallConversionReportingState } from "../enums/call_conversion_reporting_state";
import { CustomParameter } from "./custom_parameter";
import { AppStoreEnum_AppStore } from "../enums/app_store";
// Proto file describing extension types.

/**
 * Represents an App extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.AppFeedItem
 */
export interface AppFeedItem {
    /**
     * The visible text displayed when the link is rendered in an ad.
     * This string must not be empty, and the length of this string should
     * be between 1 and 25, inclusive.
     *
     * @generated from protobuf field: optional string link_text = 9;
     */
    linkText?: string;
    /**
     * The store-specific ID for the target application.
     * This string must not be empty.
     *
     * @generated from protobuf field: optional string app_id = 10;
     */
    appId?: string;
    /**
     * The application store that the target application belongs to.
     * This field is required.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.AppStoreEnum.AppStore app_store = 3;
     */
    appStore: AppStoreEnum_AppStore;
    /**
     * A list of possible final URLs after all cross domain redirects.
     * This list must not be empty.
     *
     * @generated from protobuf field: repeated string final_urls = 11;
     */
    finalUrls: string[];
    /**
     * A list of possible final mobile URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_mobile_urls = 12;
     */
    finalMobileUrls: string[];
    /**
     * URL template for constructing a tracking URL. Default value is "{lpurl}".
     *
     * @generated from protobuf field: optional string tracking_url_template = 13;
     */
    trackingUrlTemplate?: string;
    /**
     * A list of mappings to be used for substituting URL custom parameter tags in
     * the tracking_url_template, final_urls, and/or final_mobile_urls.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 7;
     */
    urlCustomParameters: CustomParameter[];
    /**
     * URL template for appending params to landing page URLs served with parallel
     * tracking.
     *
     * @generated from protobuf field: optional string final_url_suffix = 14;
     */
    finalUrlSuffix?: string;
}
/**
 * Represents a Call extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.CallFeedItem
 */
export interface CallFeedItem {
    /**
     * The advertiser's phone number to append to the ad.
     * This string must not be empty.
     *
     * @generated from protobuf field: optional string phone_number = 7;
     */
    phoneNumber?: string;
    /**
     * Uppercase two-letter country code of the advertiser's phone number.
     * This string must not be empty.
     *
     * @generated from protobuf field: optional string country_code = 8;
     */
    countryCode?: string;
    /**
     * Indicates whether call tracking is enabled. By default, call tracking is
     * not enabled.
     *
     * @generated from protobuf field: optional bool call_tracking_enabled = 9;
     */
    callTrackingEnabled?: boolean;
    /**
     * The conversion action to attribute a call conversion to. If not set a
     * default conversion action is used. This field only has effect if
     * call_tracking_enabled is set to true. Otherwise this field is ignored.
     *
     * @generated from protobuf field: optional string call_conversion_action = 10;
     */
    callConversionAction?: string;
    /**
     * If true, disable call conversion tracking. call_conversion_action should
     * not be set if this is true. Optional.
     *
     * @generated from protobuf field: optional bool call_conversion_tracking_disabled = 11;
     */
    callConversionTrackingDisabled?: boolean;
    /**
     * Enum value that indicates whether this call extension uses its own call
     * conversion setting (or just have call conversion disabled), or following
     * the account level setting.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.CallConversionReportingStateEnum.CallConversionReportingState call_conversion_reporting_state = 6;
     */
    callConversionReportingState: CallConversionReportingStateEnum_CallConversionReportingState;
}
/**
 * Represents a callout extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.CalloutFeedItem
 */
export interface CalloutFeedItem {
    /**
     * The callout text.
     * The length of this string should be between 1 and 25, inclusive.
     *
     * @generated from protobuf field: optional string callout_text = 2;
     */
    calloutText?: string;
}
/**
 * Represents a location extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.LocationFeedItem
 */
export interface LocationFeedItem {
    /**
     * The name of the business.
     *
     * @generated from protobuf field: optional string business_name = 9;
     */
    businessName?: string;
    /**
     * Line 1 of the business address.
     *
     * @generated from protobuf field: optional string address_line_1 = 10;
     */
    addressLine1?: string;
    /**
     * Line 2 of the business address.
     *
     * @generated from protobuf field: optional string address_line_2 = 11;
     */
    addressLine2?: string;
    /**
     * City of the business address.
     *
     * @generated from protobuf field: optional string city = 12;
     */
    city?: string;
    /**
     * Province of the business address.
     *
     * @generated from protobuf field: optional string province = 13;
     */
    province?: string;
    /**
     * Postal code of the business address.
     *
     * @generated from protobuf field: optional string postal_code = 14;
     */
    postalCode?: string;
    /**
     * Country code of the business address.
     *
     * @generated from protobuf field: optional string country_code = 15;
     */
    countryCode?: string;
    /**
     * Phone number of the business.
     *
     * @generated from protobuf field: optional string phone_number = 16;
     */
    phoneNumber?: string;
}
/**
 * Represents an affiliate location extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.AffiliateLocationFeedItem
 */
export interface AffiliateLocationFeedItem {
    /**
     * The name of the business.
     *
     * @generated from protobuf field: optional string business_name = 11;
     */
    businessName?: string;
    /**
     * Line 1 of the business address.
     *
     * @generated from protobuf field: optional string address_line_1 = 12;
     */
    addressLine1?: string;
    /**
     * Line 2 of the business address.
     *
     * @generated from protobuf field: optional string address_line_2 = 13;
     */
    addressLine2?: string;
    /**
     * City of the business address.
     *
     * @generated from protobuf field: optional string city = 14;
     */
    city?: string;
    /**
     * Province of the business address.
     *
     * @generated from protobuf field: optional string province = 15;
     */
    province?: string;
    /**
     * Postal code of the business address.
     *
     * @generated from protobuf field: optional string postal_code = 16;
     */
    postalCode?: string;
    /**
     * Country code of the business address.
     *
     * @generated from protobuf field: optional string country_code = 17;
     */
    countryCode?: string;
    /**
     * Phone number of the business.
     *
     * @generated from protobuf field: optional string phone_number = 18;
     */
    phoneNumber?: string;
    /**
     * Id of the retail chain that is advertised as a seller of your product.
     *
     * @generated from protobuf field: optional int64 chain_id = 19;
     */
    chainId?: bigint;
    /**
     * Name of chain.
     *
     * @generated from protobuf field: optional string chain_name = 20;
     */
    chainName?: string;
}
/**
 * An extension that users can click on to send a text message to the
 * advertiser.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.TextMessageFeedItem
 */
export interface TextMessageFeedItem {
    /**
     * The business name to prepend to the message text.
     * This field is required.
     *
     * @generated from protobuf field: optional string business_name = 6;
     */
    businessName?: string;
    /**
     * Uppercase two-letter country code of the advertiser's phone number.
     * This field is required.
     *
     * @generated from protobuf field: optional string country_code = 7;
     */
    countryCode?: string;
    /**
     * The advertiser's phone number the message will be sent to. Required.
     *
     * @generated from protobuf field: optional string phone_number = 8;
     */
    phoneNumber?: string;
    /**
     * The text to show in the ad.
     * This field is required.
     *
     * @generated from protobuf field: optional string text = 9;
     */
    text?: string;
    /**
     * The message extension_text populated in the messaging app.
     *
     * @generated from protobuf field: optional string extension_text = 10;
     */
    extensionText?: string;
}
/**
 * Represents a Price extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.PriceFeedItem
 */
export interface PriceFeedItem {
    /**
     * Price extension type of this extension.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.PriceExtensionTypeEnum.PriceExtensionType type = 1;
     */
    type: PriceExtensionTypeEnum_PriceExtensionType;
    /**
     * Price qualifier for all offers of this price extension.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.PriceExtensionPriceQualifierEnum.PriceExtensionPriceQualifier price_qualifier = 2;
     */
    priceQualifier: PriceExtensionPriceQualifierEnum_PriceExtensionPriceQualifier;
    /**
     * Tracking URL template for all offers of this price extension.
     *
     * @generated from protobuf field: optional string tracking_url_template = 7;
     */
    trackingUrlTemplate?: string;
    /**
     * The code of the language used for this price extension.
     *
     * @generated from protobuf field: optional string language_code = 8;
     */
    languageCode?: string;
    /**
     * The price offerings in this price extension.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.common.PriceOffer price_offerings = 5;
     */
    priceOfferings: PriceOffer[];
    /**
     * Tracking URL template for all offers of this price extension.
     *
     * @generated from protobuf field: optional string final_url_suffix = 9;
     */
    finalUrlSuffix?: string;
}
/**
 * Represents one price offer in a price extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.PriceOffer
 */
export interface PriceOffer {
    /**
     * Header text of this offer.
     *
     * @generated from protobuf field: optional string header = 7;
     */
    header?: string;
    /**
     * Description text of this offer.
     *
     * @generated from protobuf field: optional string description = 8;
     */
    description?: string;
    /**
     * Price value of this offer.
     *
     * @generated from protobuf field: google.ads.googleads.v11.common.Money price = 3;
     */
    price?: Money;
    /**
     * Price unit for this offer.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.PriceExtensionPriceUnitEnum.PriceExtensionPriceUnit unit = 4;
     */
    unit: PriceExtensionPriceUnitEnum_PriceExtensionPriceUnit;
    /**
     * A list of possible final URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_urls = 9;
     */
    finalUrls: string[];
    /**
     * A list of possible final mobile URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_mobile_urls = 10;
     */
    finalMobileUrls: string[];
}
/**
 * Represents a Promotion extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.PromotionFeedItem
 */
export interface PromotionFeedItem {
    /**
     * A freeform description of what the promotion is targeting.
     * This field is required.
     *
     * @generated from protobuf field: optional string promotion_target = 16;
     */
    promotionTarget?: string;
    /**
     * Enum that modifies the qualification of the discount.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.PromotionExtensionDiscountModifierEnum.PromotionExtensionDiscountModifier discount_modifier = 2;
     */
    discountModifier: PromotionExtensionDiscountModifierEnum_PromotionExtensionDiscountModifier;
    /**
     * Start date of when the promotion is eligible to be redeemed.
     *
     * @generated from protobuf field: optional string promotion_start_date = 19;
     */
    promotionStartDate?: string;
    /**
     * Last date when the promotion is eligible to be redeemed.
     *
     * @generated from protobuf field: optional string promotion_end_date = 20;
     */
    promotionEndDate?: string;
    /**
     * The occasion the promotion was intended for.
     * If an occasion is set, the redemption window will need to fall within
     * the date range associated with the occasion.
     *
     * @generated from protobuf field: google.ads.googleads.v11.enums.PromotionExtensionOccasionEnum.PromotionExtensionOccasion occasion = 9;
     */
    occasion: PromotionExtensionOccasionEnum_PromotionExtensionOccasion;
    /**
     * A list of possible final URLs after all cross domain redirects.
     * This field is required.
     *
     * @generated from protobuf field: repeated string final_urls = 21;
     */
    finalUrls: string[];
    /**
     * A list of possible final mobile URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_mobile_urls = 22;
     */
    finalMobileUrls: string[];
    /**
     * URL template for constructing a tracking URL.
     *
     * @generated from protobuf field: optional string tracking_url_template = 23;
     */
    trackingUrlTemplate?: string;
    /**
     * A list of mappings to be used for substituting URL custom parameter tags in
     * the tracking_url_template, final_urls, and/or final_mobile_urls.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 13;
     */
    urlCustomParameters: CustomParameter[];
    /**
     * URL template for appending params to landing page URLs served with parallel
     * tracking.
     *
     * @generated from protobuf field: optional string final_url_suffix = 24;
     */
    finalUrlSuffix?: string;
    /**
     * The language of the promotion.
     * Represented as BCP 47 language tag.
     *
     * @generated from protobuf field: optional string language_code = 25;
     */
    languageCode?: string;
    /**
     * @generated from protobuf oneof: discount_type
     */
    discountType: {
        oneofKind: "percentOff";
        /**
         * Percentage off discount in the promotion in micros.
         * One million is equivalent to one percent.
         * Either this or money_off_amount is required.
         *
         * @generated from protobuf field: int64 percent_off = 17;
         */
        percentOff: bigint;
    } | {
        oneofKind: "moneyAmountOff";
        /**
         * Money amount off for discount in the promotion.
         * Either this or percent_off is required.
         *
         * @generated from protobuf field: google.ads.googleads.v11.common.Money money_amount_off = 4;
         */
        moneyAmountOff: Money;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf oneof: promotion_trigger
     */
    promotionTrigger: {
        oneofKind: "promotionCode";
        /**
         * A code the user should use in order to be eligible for the promotion.
         *
         * @generated from protobuf field: string promotion_code = 18;
         */
        promotionCode: string;
    } | {
        oneofKind: "ordersOverAmount";
        /**
         * The amount the total order needs to be for the user to be eligible for
         * the promotion.
         *
         * @generated from protobuf field: google.ads.googleads.v11.common.Money orders_over_amount = 6;
         */
        ordersOverAmount: Money;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Represents a structured snippet extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.StructuredSnippetFeedItem
 */
export interface StructuredSnippetFeedItem {
    /**
     * The header of the snippet.
     * This string must not be empty.
     *
     * @generated from protobuf field: optional string header = 3;
     */
    header?: string;
    /**
     * The values in the snippet.
     * The maximum size of this collection is 10.
     *
     * @generated from protobuf field: repeated string values = 4;
     */
    values: string[];
}
/**
 * Represents a sitelink extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.SitelinkFeedItem
 */
export interface SitelinkFeedItem {
    /**
     * URL display text for the sitelink.
     * The length of this string should be between 1 and 25, inclusive.
     *
     * @generated from protobuf field: optional string link_text = 9;
     */
    linkText?: string;
    /**
     * First line of the description for the sitelink.
     * If this value is set, line2 must also be set.
     * The length of this string should be between 0 and 35, inclusive.
     *
     * @generated from protobuf field: optional string line1 = 10;
     */
    line1?: string;
    /**
     * Second line of the description for the sitelink.
     * If this value is set, line1 must also be set.
     * The length of this string should be between 0 and 35, inclusive.
     *
     * @generated from protobuf field: optional string line2 = 11;
     */
    line2?: string;
    /**
     * A list of possible final URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_urls = 12;
     */
    finalUrls: string[];
    /**
     * A list of possible final mobile URLs after all cross domain redirects.
     *
     * @generated from protobuf field: repeated string final_mobile_urls = 13;
     */
    finalMobileUrls: string[];
    /**
     * URL template for constructing a tracking URL.
     *
     * @generated from protobuf field: optional string tracking_url_template = 14;
     */
    trackingUrlTemplate?: string;
    /**
     * A list of mappings to be used for substituting URL custom parameter tags in
     * the tracking_url_template, final_urls, and/or final_mobile_urls.
     *
     * @generated from protobuf field: repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 7;
     */
    urlCustomParameters: CustomParameter[];
    /**
     * Final URL suffix to be appended to landing page URLs served with
     * parallel tracking.
     *
     * @generated from protobuf field: optional string final_url_suffix = 15;
     */
    finalUrlSuffix?: string;
}
/**
 * Represents a hotel callout extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.HotelCalloutFeedItem
 */
export interface HotelCalloutFeedItem {
    /**
     * The callout text.
     * The length of this string should be between 1 and 25, inclusive.
     *
     * @generated from protobuf field: optional string text = 3;
     */
    text?: string;
    /**
     * The language of the hotel callout text.
     * IETF BCP 47 compliant language code.
     *
     * @generated from protobuf field: optional string language_code = 4;
     */
    languageCode?: string;
}
/**
 * Represents an advertiser provided image extension.
 *
 * @generated from protobuf message google.ads.googleads.v11.common.ImageFeedItem
 */
export interface ImageFeedItem {
    /**
     * Required. Resource name of the image asset.
     *
     * @generated from protobuf field: string image_asset = 1;
     */
    imageAsset: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AppFeedItem$Type extends MessageType<AppFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.AppFeedItem", [
            { no: 9, name: "link_text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "app_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "app_store", kind: "enum", T: () => ["google.ads.googleads.v11.enums.AppStoreEnum.AppStore", AppStoreEnum_AppStore] },
            { no: 11, name: "final_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "final_mobile_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "tracking_url_template", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "url_custom_parameters", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CustomParameter },
            { no: 14, name: "final_url_suffix", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AppFeedItem>): AppFeedItem {
        const message = { appStore: 0, finalUrls: [], finalMobileUrls: [], urlCustomParameters: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AppFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AppFeedItem): AppFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string link_text */ 9:
                    message.linkText = reader.string();
                    break;
                case /* optional string app_id */ 10:
                    message.appId = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.AppStoreEnum.AppStore app_store */ 3:
                    message.appStore = reader.int32();
                    break;
                case /* repeated string final_urls */ 11:
                    message.finalUrls.push(reader.string());
                    break;
                case /* repeated string final_mobile_urls */ 12:
                    message.finalMobileUrls.push(reader.string());
                    break;
                case /* optional string tracking_url_template */ 13:
                    message.trackingUrlTemplate = reader.string();
                    break;
                case /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters */ 7:
                    message.urlCustomParameters.push(CustomParameter.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string final_url_suffix */ 14:
                    message.finalUrlSuffix = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AppFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string link_text = 9; */
        if (message.linkText !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.linkText);
        /* optional string app_id = 10; */
        if (message.appId !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.appId);
        /* google.ads.googleads.v11.enums.AppStoreEnum.AppStore app_store = 3; */
        if (message.appStore !== 0)
            writer.tag(3, WireType.Varint).int32(message.appStore);
        /* repeated string final_urls = 11; */
        for (let i = 0; i < message.finalUrls.length; i++)
            writer.tag(11, WireType.LengthDelimited).string(message.finalUrls[i]);
        /* repeated string final_mobile_urls = 12; */
        for (let i = 0; i < message.finalMobileUrls.length; i++)
            writer.tag(12, WireType.LengthDelimited).string(message.finalMobileUrls[i]);
        /* optional string tracking_url_template = 13; */
        if (message.trackingUrlTemplate !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.trackingUrlTemplate);
        /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 7; */
        for (let i = 0; i < message.urlCustomParameters.length; i++)
            CustomParameter.internalBinaryWrite(message.urlCustomParameters[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional string final_url_suffix = 14; */
        if (message.finalUrlSuffix !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.finalUrlSuffix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.AppFeedItem
 */
export const AppFeedItem = new AppFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CallFeedItem$Type extends MessageType<CallFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.CallFeedItem", [
            { no: 7, name: "phone_number", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "country_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "call_tracking_enabled", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "call_conversion_action", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "call_conversion_tracking_disabled", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "call_conversion_reporting_state", kind: "enum", T: () => ["google.ads.googleads.v11.enums.CallConversionReportingStateEnum.CallConversionReportingState", CallConversionReportingStateEnum_CallConversionReportingState] }
        ]);
    }
    create(value?: PartialMessage<CallFeedItem>): CallFeedItem {
        const message = { callConversionReportingState: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CallFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CallFeedItem): CallFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string phone_number */ 7:
                    message.phoneNumber = reader.string();
                    break;
                case /* optional string country_code */ 8:
                    message.countryCode = reader.string();
                    break;
                case /* optional bool call_tracking_enabled */ 9:
                    message.callTrackingEnabled = reader.bool();
                    break;
                case /* optional string call_conversion_action */ 10:
                    message.callConversionAction = reader.string();
                    break;
                case /* optional bool call_conversion_tracking_disabled */ 11:
                    message.callConversionTrackingDisabled = reader.bool();
                    break;
                case /* google.ads.googleads.v11.enums.CallConversionReportingStateEnum.CallConversionReportingState call_conversion_reporting_state */ 6:
                    message.callConversionReportingState = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CallFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string phone_number = 7; */
        if (message.phoneNumber !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.phoneNumber);
        /* optional string country_code = 8; */
        if (message.countryCode !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.countryCode);
        /* optional bool call_tracking_enabled = 9; */
        if (message.callTrackingEnabled !== undefined)
            writer.tag(9, WireType.Varint).bool(message.callTrackingEnabled);
        /* optional string call_conversion_action = 10; */
        if (message.callConversionAction !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.callConversionAction);
        /* optional bool call_conversion_tracking_disabled = 11; */
        if (message.callConversionTrackingDisabled !== undefined)
            writer.tag(11, WireType.Varint).bool(message.callConversionTrackingDisabled);
        /* google.ads.googleads.v11.enums.CallConversionReportingStateEnum.CallConversionReportingState call_conversion_reporting_state = 6; */
        if (message.callConversionReportingState !== 0)
            writer.tag(6, WireType.Varint).int32(message.callConversionReportingState);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.CallFeedItem
 */
export const CallFeedItem = new CallFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CalloutFeedItem$Type extends MessageType<CalloutFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.CalloutFeedItem", [
            { no: 2, name: "callout_text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CalloutFeedItem>): CalloutFeedItem {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CalloutFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CalloutFeedItem): CalloutFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string callout_text */ 2:
                    message.calloutText = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CalloutFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string callout_text = 2; */
        if (message.calloutText !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.calloutText);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.CalloutFeedItem
 */
export const CalloutFeedItem = new CalloutFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocationFeedItem$Type extends MessageType<LocationFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.LocationFeedItem", [
            { no: 9, name: "business_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "address_line_1", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "address_line_2", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "city", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "province", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "postal_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "country_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "phone_number", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocationFeedItem>): LocationFeedItem {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<LocationFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocationFeedItem): LocationFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string business_name */ 9:
                    message.businessName = reader.string();
                    break;
                case /* optional string address_line_1 */ 10:
                    message.addressLine1 = reader.string();
                    break;
                case /* optional string address_line_2 */ 11:
                    message.addressLine2 = reader.string();
                    break;
                case /* optional string city */ 12:
                    message.city = reader.string();
                    break;
                case /* optional string province */ 13:
                    message.province = reader.string();
                    break;
                case /* optional string postal_code */ 14:
                    message.postalCode = reader.string();
                    break;
                case /* optional string country_code */ 15:
                    message.countryCode = reader.string();
                    break;
                case /* optional string phone_number */ 16:
                    message.phoneNumber = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocationFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string business_name = 9; */
        if (message.businessName !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.businessName);
        /* optional string address_line_1 = 10; */
        if (message.addressLine1 !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.addressLine1);
        /* optional string address_line_2 = 11; */
        if (message.addressLine2 !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.addressLine2);
        /* optional string city = 12; */
        if (message.city !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.city);
        /* optional string province = 13; */
        if (message.province !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.province);
        /* optional string postal_code = 14; */
        if (message.postalCode !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.postalCode);
        /* optional string country_code = 15; */
        if (message.countryCode !== undefined)
            writer.tag(15, WireType.LengthDelimited).string(message.countryCode);
        /* optional string phone_number = 16; */
        if (message.phoneNumber !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.phoneNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.LocationFeedItem
 */
export const LocationFeedItem = new LocationFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AffiliateLocationFeedItem$Type extends MessageType<AffiliateLocationFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.AffiliateLocationFeedItem", [
            { no: 11, name: "business_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "address_line_1", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "address_line_2", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "city", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "province", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "postal_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "country_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "phone_number", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "chain_id", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 20, name: "chain_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AffiliateLocationFeedItem>): AffiliateLocationFeedItem {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AffiliateLocationFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AffiliateLocationFeedItem): AffiliateLocationFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string business_name */ 11:
                    message.businessName = reader.string();
                    break;
                case /* optional string address_line_1 */ 12:
                    message.addressLine1 = reader.string();
                    break;
                case /* optional string address_line_2 */ 13:
                    message.addressLine2 = reader.string();
                    break;
                case /* optional string city */ 14:
                    message.city = reader.string();
                    break;
                case /* optional string province */ 15:
                    message.province = reader.string();
                    break;
                case /* optional string postal_code */ 16:
                    message.postalCode = reader.string();
                    break;
                case /* optional string country_code */ 17:
                    message.countryCode = reader.string();
                    break;
                case /* optional string phone_number */ 18:
                    message.phoneNumber = reader.string();
                    break;
                case /* optional int64 chain_id */ 19:
                    message.chainId = reader.int64().toBigInt();
                    break;
                case /* optional string chain_name */ 20:
                    message.chainName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AffiliateLocationFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string business_name = 11; */
        if (message.businessName !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.businessName);
        /* optional string address_line_1 = 12; */
        if (message.addressLine1 !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.addressLine1);
        /* optional string address_line_2 = 13; */
        if (message.addressLine2 !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.addressLine2);
        /* optional string city = 14; */
        if (message.city !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.city);
        /* optional string province = 15; */
        if (message.province !== undefined)
            writer.tag(15, WireType.LengthDelimited).string(message.province);
        /* optional string postal_code = 16; */
        if (message.postalCode !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.postalCode);
        /* optional string country_code = 17; */
        if (message.countryCode !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.countryCode);
        /* optional string phone_number = 18; */
        if (message.phoneNumber !== undefined)
            writer.tag(18, WireType.LengthDelimited).string(message.phoneNumber);
        /* optional int64 chain_id = 19; */
        if (message.chainId !== undefined)
            writer.tag(19, WireType.Varint).int64(message.chainId);
        /* optional string chain_name = 20; */
        if (message.chainName !== undefined)
            writer.tag(20, WireType.LengthDelimited).string(message.chainName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.AffiliateLocationFeedItem
 */
export const AffiliateLocationFeedItem = new AffiliateLocationFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TextMessageFeedItem$Type extends MessageType<TextMessageFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.TextMessageFeedItem", [
            { no: 6, name: "business_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "country_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "phone_number", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "extension_text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TextMessageFeedItem>): TextMessageFeedItem {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TextMessageFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextMessageFeedItem): TextMessageFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string business_name */ 6:
                    message.businessName = reader.string();
                    break;
                case /* optional string country_code */ 7:
                    message.countryCode = reader.string();
                    break;
                case /* optional string phone_number */ 8:
                    message.phoneNumber = reader.string();
                    break;
                case /* optional string text */ 9:
                    message.text = reader.string();
                    break;
                case /* optional string extension_text */ 10:
                    message.extensionText = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TextMessageFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string business_name = 6; */
        if (message.businessName !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.businessName);
        /* optional string country_code = 7; */
        if (message.countryCode !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.countryCode);
        /* optional string phone_number = 8; */
        if (message.phoneNumber !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.phoneNumber);
        /* optional string text = 9; */
        if (message.text !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.text);
        /* optional string extension_text = 10; */
        if (message.extensionText !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.extensionText);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.TextMessageFeedItem
 */
export const TextMessageFeedItem = new TextMessageFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PriceFeedItem$Type extends MessageType<PriceFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.PriceFeedItem", [
            { no: 1, name: "type", kind: "enum", T: () => ["google.ads.googleads.v11.enums.PriceExtensionTypeEnum.PriceExtensionType", PriceExtensionTypeEnum_PriceExtensionType] },
            { no: 2, name: "price_qualifier", kind: "enum", T: () => ["google.ads.googleads.v11.enums.PriceExtensionPriceQualifierEnum.PriceExtensionPriceQualifier", PriceExtensionPriceQualifierEnum_PriceExtensionPriceQualifier] },
            { no: 7, name: "tracking_url_template", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "language_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "price_offerings", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PriceOffer },
            { no: 9, name: "final_url_suffix", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PriceFeedItem>): PriceFeedItem {
        const message = { type: 0, priceQualifier: 0, priceOfferings: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PriceFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PriceFeedItem): PriceFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.ads.googleads.v11.enums.PriceExtensionTypeEnum.PriceExtensionType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* google.ads.googleads.v11.enums.PriceExtensionPriceQualifierEnum.PriceExtensionPriceQualifier price_qualifier */ 2:
                    message.priceQualifier = reader.int32();
                    break;
                case /* optional string tracking_url_template */ 7:
                    message.trackingUrlTemplate = reader.string();
                    break;
                case /* optional string language_code */ 8:
                    message.languageCode = reader.string();
                    break;
                case /* repeated google.ads.googleads.v11.common.PriceOffer price_offerings */ 5:
                    message.priceOfferings.push(PriceOffer.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string final_url_suffix */ 9:
                    message.finalUrlSuffix = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PriceFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.ads.googleads.v11.enums.PriceExtensionTypeEnum.PriceExtensionType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* google.ads.googleads.v11.enums.PriceExtensionPriceQualifierEnum.PriceExtensionPriceQualifier price_qualifier = 2; */
        if (message.priceQualifier !== 0)
            writer.tag(2, WireType.Varint).int32(message.priceQualifier);
        /* optional string tracking_url_template = 7; */
        if (message.trackingUrlTemplate !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.trackingUrlTemplate);
        /* optional string language_code = 8; */
        if (message.languageCode !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.languageCode);
        /* repeated google.ads.googleads.v11.common.PriceOffer price_offerings = 5; */
        for (let i = 0; i < message.priceOfferings.length; i++)
            PriceOffer.internalBinaryWrite(message.priceOfferings[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional string final_url_suffix = 9; */
        if (message.finalUrlSuffix !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.finalUrlSuffix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.PriceFeedItem
 */
export const PriceFeedItem = new PriceFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PriceOffer$Type extends MessageType<PriceOffer> {
    constructor() {
        super("google.ads.googleads.v11.common.PriceOffer", [
            { no: 7, name: "header", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price", kind: "message", T: () => Money },
            { no: 4, name: "unit", kind: "enum", T: () => ["google.ads.googleads.v11.enums.PriceExtensionPriceUnitEnum.PriceExtensionPriceUnit", PriceExtensionPriceUnitEnum_PriceExtensionPriceUnit] },
            { no: 9, name: "final_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "final_mobile_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PriceOffer>): PriceOffer {
        const message = { unit: 0, finalUrls: [], finalMobileUrls: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PriceOffer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PriceOffer): PriceOffer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string header */ 7:
                    message.header = reader.string();
                    break;
                case /* optional string description */ 8:
                    message.description = reader.string();
                    break;
                case /* google.ads.googleads.v11.common.Money price */ 3:
                    message.price = Money.internalBinaryRead(reader, reader.uint32(), options, message.price);
                    break;
                case /* google.ads.googleads.v11.enums.PriceExtensionPriceUnitEnum.PriceExtensionPriceUnit unit */ 4:
                    message.unit = reader.int32();
                    break;
                case /* repeated string final_urls */ 9:
                    message.finalUrls.push(reader.string());
                    break;
                case /* repeated string final_mobile_urls */ 10:
                    message.finalMobileUrls.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PriceOffer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string header = 7; */
        if (message.header !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.header);
        /* optional string description = 8; */
        if (message.description !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.description);
        /* google.ads.googleads.v11.common.Money price = 3; */
        if (message.price)
            Money.internalBinaryWrite(message.price, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.ads.googleads.v11.enums.PriceExtensionPriceUnitEnum.PriceExtensionPriceUnit unit = 4; */
        if (message.unit !== 0)
            writer.tag(4, WireType.Varint).int32(message.unit);
        /* repeated string final_urls = 9; */
        for (let i = 0; i < message.finalUrls.length; i++)
            writer.tag(9, WireType.LengthDelimited).string(message.finalUrls[i]);
        /* repeated string final_mobile_urls = 10; */
        for (let i = 0; i < message.finalMobileUrls.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.finalMobileUrls[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.PriceOffer
 */
export const PriceOffer = new PriceOffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PromotionFeedItem$Type extends MessageType<PromotionFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.PromotionFeedItem", [
            { no: 16, name: "promotion_target", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "discount_modifier", kind: "enum", T: () => ["google.ads.googleads.v11.enums.PromotionExtensionDiscountModifierEnum.PromotionExtensionDiscountModifier", PromotionExtensionDiscountModifierEnum_PromotionExtensionDiscountModifier] },
            { no: 19, name: "promotion_start_date", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "promotion_end_date", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "occasion", kind: "enum", T: () => ["google.ads.googleads.v11.enums.PromotionExtensionOccasionEnum.PromotionExtensionOccasion", PromotionExtensionOccasionEnum_PromotionExtensionOccasion] },
            { no: 21, name: "final_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "final_mobile_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "tracking_url_template", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "url_custom_parameters", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CustomParameter },
            { no: 24, name: "final_url_suffix", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "language_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "percent_off", kind: "scalar", oneof: "discountType", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "money_amount_off", kind: "message", oneof: "discountType", T: () => Money },
            { no: 18, name: "promotion_code", kind: "scalar", oneof: "promotionTrigger", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "orders_over_amount", kind: "message", oneof: "promotionTrigger", T: () => Money }
        ]);
    }
    create(value?: PartialMessage<PromotionFeedItem>): PromotionFeedItem {
        const message = { discountModifier: 0, occasion: 0, finalUrls: [], finalMobileUrls: [], urlCustomParameters: [], discountType: { oneofKind: undefined }, promotionTrigger: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PromotionFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PromotionFeedItem): PromotionFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string promotion_target */ 16:
                    message.promotionTarget = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.PromotionExtensionDiscountModifierEnum.PromotionExtensionDiscountModifier discount_modifier */ 2:
                    message.discountModifier = reader.int32();
                    break;
                case /* optional string promotion_start_date */ 19:
                    message.promotionStartDate = reader.string();
                    break;
                case /* optional string promotion_end_date */ 20:
                    message.promotionEndDate = reader.string();
                    break;
                case /* google.ads.googleads.v11.enums.PromotionExtensionOccasionEnum.PromotionExtensionOccasion occasion */ 9:
                    message.occasion = reader.int32();
                    break;
                case /* repeated string final_urls */ 21:
                    message.finalUrls.push(reader.string());
                    break;
                case /* repeated string final_mobile_urls */ 22:
                    message.finalMobileUrls.push(reader.string());
                    break;
                case /* optional string tracking_url_template */ 23:
                    message.trackingUrlTemplate = reader.string();
                    break;
                case /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters */ 13:
                    message.urlCustomParameters.push(CustomParameter.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string final_url_suffix */ 24:
                    message.finalUrlSuffix = reader.string();
                    break;
                case /* optional string language_code */ 25:
                    message.languageCode = reader.string();
                    break;
                case /* int64 percent_off */ 17:
                    message.discountType = {
                        oneofKind: "percentOff",
                        percentOff: reader.int64().toBigInt()
                    };
                    break;
                case /* google.ads.googleads.v11.common.Money money_amount_off */ 4:
                    message.discountType = {
                        oneofKind: "moneyAmountOff",
                        moneyAmountOff: Money.internalBinaryRead(reader, reader.uint32(), options, (message.discountType as any).moneyAmountOff)
                    };
                    break;
                case /* string promotion_code */ 18:
                    message.promotionTrigger = {
                        oneofKind: "promotionCode",
                        promotionCode: reader.string()
                    };
                    break;
                case /* google.ads.googleads.v11.common.Money orders_over_amount */ 6:
                    message.promotionTrigger = {
                        oneofKind: "ordersOverAmount",
                        ordersOverAmount: Money.internalBinaryRead(reader, reader.uint32(), options, (message.promotionTrigger as any).ordersOverAmount)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PromotionFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string promotion_target = 16; */
        if (message.promotionTarget !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.promotionTarget);
        /* google.ads.googleads.v11.enums.PromotionExtensionDiscountModifierEnum.PromotionExtensionDiscountModifier discount_modifier = 2; */
        if (message.discountModifier !== 0)
            writer.tag(2, WireType.Varint).int32(message.discountModifier);
        /* optional string promotion_start_date = 19; */
        if (message.promotionStartDate !== undefined)
            writer.tag(19, WireType.LengthDelimited).string(message.promotionStartDate);
        /* optional string promotion_end_date = 20; */
        if (message.promotionEndDate !== undefined)
            writer.tag(20, WireType.LengthDelimited).string(message.promotionEndDate);
        /* google.ads.googleads.v11.enums.PromotionExtensionOccasionEnum.PromotionExtensionOccasion occasion = 9; */
        if (message.occasion !== 0)
            writer.tag(9, WireType.Varint).int32(message.occasion);
        /* repeated string final_urls = 21; */
        for (let i = 0; i < message.finalUrls.length; i++)
            writer.tag(21, WireType.LengthDelimited).string(message.finalUrls[i]);
        /* repeated string final_mobile_urls = 22; */
        for (let i = 0; i < message.finalMobileUrls.length; i++)
            writer.tag(22, WireType.LengthDelimited).string(message.finalMobileUrls[i]);
        /* optional string tracking_url_template = 23; */
        if (message.trackingUrlTemplate !== undefined)
            writer.tag(23, WireType.LengthDelimited).string(message.trackingUrlTemplate);
        /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 13; */
        for (let i = 0; i < message.urlCustomParameters.length; i++)
            CustomParameter.internalBinaryWrite(message.urlCustomParameters[i], writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* optional string final_url_suffix = 24; */
        if (message.finalUrlSuffix !== undefined)
            writer.tag(24, WireType.LengthDelimited).string(message.finalUrlSuffix);
        /* optional string language_code = 25; */
        if (message.languageCode !== undefined)
            writer.tag(25, WireType.LengthDelimited).string(message.languageCode);
        /* int64 percent_off = 17; */
        if (message.discountType.oneofKind === "percentOff")
            writer.tag(17, WireType.Varint).int64(message.discountType.percentOff);
        /* google.ads.googleads.v11.common.Money money_amount_off = 4; */
        if (message.discountType.oneofKind === "moneyAmountOff")
            Money.internalBinaryWrite(message.discountType.moneyAmountOff, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string promotion_code = 18; */
        if (message.promotionTrigger.oneofKind === "promotionCode")
            writer.tag(18, WireType.LengthDelimited).string(message.promotionTrigger.promotionCode);
        /* google.ads.googleads.v11.common.Money orders_over_amount = 6; */
        if (message.promotionTrigger.oneofKind === "ordersOverAmount")
            Money.internalBinaryWrite(message.promotionTrigger.ordersOverAmount, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.PromotionFeedItem
 */
export const PromotionFeedItem = new PromotionFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StructuredSnippetFeedItem$Type extends MessageType<StructuredSnippetFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.StructuredSnippetFeedItem", [
            { no: 3, name: "header", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StructuredSnippetFeedItem>): StructuredSnippetFeedItem {
        const message = { values: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<StructuredSnippetFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StructuredSnippetFeedItem): StructuredSnippetFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string header */ 3:
                    message.header = reader.string();
                    break;
                case /* repeated string values */ 4:
                    message.values.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StructuredSnippetFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string header = 3; */
        if (message.header !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.header);
        /* repeated string values = 4; */
        for (let i = 0; i < message.values.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.values[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.StructuredSnippetFeedItem
 */
export const StructuredSnippetFeedItem = new StructuredSnippetFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SitelinkFeedItem$Type extends MessageType<SitelinkFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.SitelinkFeedItem", [
            { no: 9, name: "link_text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "line1", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "line2", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "final_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "final_mobile_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "tracking_url_template", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "url_custom_parameters", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CustomParameter },
            { no: 15, name: "final_url_suffix", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SitelinkFeedItem>): SitelinkFeedItem {
        const message = { finalUrls: [], finalMobileUrls: [], urlCustomParameters: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SitelinkFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SitelinkFeedItem): SitelinkFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string link_text */ 9:
                    message.linkText = reader.string();
                    break;
                case /* optional string line1 */ 10:
                    message.line1 = reader.string();
                    break;
                case /* optional string line2 */ 11:
                    message.line2 = reader.string();
                    break;
                case /* repeated string final_urls */ 12:
                    message.finalUrls.push(reader.string());
                    break;
                case /* repeated string final_mobile_urls */ 13:
                    message.finalMobileUrls.push(reader.string());
                    break;
                case /* optional string tracking_url_template */ 14:
                    message.trackingUrlTemplate = reader.string();
                    break;
                case /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters */ 7:
                    message.urlCustomParameters.push(CustomParameter.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string final_url_suffix */ 15:
                    message.finalUrlSuffix = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SitelinkFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string link_text = 9; */
        if (message.linkText !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.linkText);
        /* optional string line1 = 10; */
        if (message.line1 !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.line1);
        /* optional string line2 = 11; */
        if (message.line2 !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.line2);
        /* repeated string final_urls = 12; */
        for (let i = 0; i < message.finalUrls.length; i++)
            writer.tag(12, WireType.LengthDelimited).string(message.finalUrls[i]);
        /* repeated string final_mobile_urls = 13; */
        for (let i = 0; i < message.finalMobileUrls.length; i++)
            writer.tag(13, WireType.LengthDelimited).string(message.finalMobileUrls[i]);
        /* optional string tracking_url_template = 14; */
        if (message.trackingUrlTemplate !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.trackingUrlTemplate);
        /* repeated google.ads.googleads.v11.common.CustomParameter url_custom_parameters = 7; */
        for (let i = 0; i < message.urlCustomParameters.length; i++)
            CustomParameter.internalBinaryWrite(message.urlCustomParameters[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional string final_url_suffix = 15; */
        if (message.finalUrlSuffix !== undefined)
            writer.tag(15, WireType.LengthDelimited).string(message.finalUrlSuffix);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.SitelinkFeedItem
 */
export const SitelinkFeedItem = new SitelinkFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HotelCalloutFeedItem$Type extends MessageType<HotelCalloutFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.HotelCalloutFeedItem", [
            { no: 3, name: "text", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "language_code", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HotelCalloutFeedItem>): HotelCalloutFeedItem {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HotelCalloutFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HotelCalloutFeedItem): HotelCalloutFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string text */ 3:
                    message.text = reader.string();
                    break;
                case /* optional string language_code */ 4:
                    message.languageCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HotelCalloutFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string text = 3; */
        if (message.text !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.text);
        /* optional string language_code = 4; */
        if (message.languageCode !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.languageCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.HotelCalloutFeedItem
 */
export const HotelCalloutFeedItem = new HotelCalloutFeedItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImageFeedItem$Type extends MessageType<ImageFeedItem> {
    constructor() {
        super("google.ads.googleads.v11.common.ImageFeedItem", [
            { no: 1, name: "image_asset", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "google.api.field_behavior": ["REQUIRED"], "google.api.resource_reference": { type: "googleads.googleapis.com/Asset" } } }
        ]);
    }
    create(value?: PartialMessage<ImageFeedItem>): ImageFeedItem {
        const message = { imageAsset: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ImageFeedItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImageFeedItem): ImageFeedItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string image_asset */ 1:
                    message.imageAsset = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImageFeedItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string image_asset = 1; */
        if (message.imageAsset !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.imageAsset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.common.ImageFeedItem
 */
export const ImageFeedItem = new ImageFeedItem$Type();
