// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/errors/campaign_draft_error.proto" (package "google.ads.googleads.v11.errors", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing campaign draft errors.

/**
 * Container for enum describing possible campaign draft errors.
 *
 * @generated from protobuf message google.ads.googleads.v11.errors.CampaignDraftErrorEnum
 */
export interface CampaignDraftErrorEnum {
}
/**
 * Enum describing possible campaign draft errors.
 *
 * @generated from protobuf enum google.ads.googleads.v11.errors.CampaignDraftErrorEnum.CampaignDraftError
 */
export enum CampaignDraftErrorEnum_CampaignDraftError {
    /**
     * Enum unspecified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The received error code is not known in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * A draft with this name already exists for this campaign.
     *
     * @generated from protobuf enum value: DUPLICATE_DRAFT_NAME = 2;
     */
    DUPLICATE_DRAFT_NAME = 2,
    /**
     * The draft is removed and cannot be transitioned to another status.
     *
     * @generated from protobuf enum value: INVALID_STATUS_TRANSITION_FROM_REMOVED = 3;
     */
    INVALID_STATUS_TRANSITION_FROM_REMOVED = 3,
    /**
     * The draft has been promoted and cannot be transitioned to the specified
     * status.
     *
     * @generated from protobuf enum value: INVALID_STATUS_TRANSITION_FROM_PROMOTED = 4;
     */
    INVALID_STATUS_TRANSITION_FROM_PROMOTED = 4,
    /**
     * The draft has failed to be promoted and cannot be transitioned to the
     * specified status.
     *
     * @generated from protobuf enum value: INVALID_STATUS_TRANSITION_FROM_PROMOTE_FAILED = 5;
     */
    INVALID_STATUS_TRANSITION_FROM_PROMOTE_FAILED = 5,
    /**
     * This customer is not allowed to create drafts.
     *
     * @generated from protobuf enum value: CUSTOMER_CANNOT_CREATE_DRAFT = 6;
     */
    CUSTOMER_CANNOT_CREATE_DRAFT = 6,
    /**
     * This campaign is not allowed to create drafts.
     *
     * @generated from protobuf enum value: CAMPAIGN_CANNOT_CREATE_DRAFT = 7;
     */
    CAMPAIGN_CANNOT_CREATE_DRAFT = 7,
    /**
     * This modification cannot be made on a draft.
     *
     * @generated from protobuf enum value: INVALID_DRAFT_CHANGE = 8;
     */
    INVALID_DRAFT_CHANGE = 8,
    /**
     * The draft cannot be transitioned to the specified status from its
     * current status.
     *
     * @generated from protobuf enum value: INVALID_STATUS_TRANSITION = 9;
     */
    INVALID_STATUS_TRANSITION = 9,
    /**
     * The campaign has reached the maximum number of drafts that can be created
     * for a campaign throughout its lifetime. No additional drafts can be
     * created for this campaign. Removed drafts also count towards this limit.
     *
     * @generated from protobuf enum value: MAX_NUMBER_OF_DRAFTS_PER_CAMPAIGN_REACHED = 10;
     */
    MAX_NUMBER_OF_DRAFTS_PER_CAMPAIGN_REACHED = 10,
    /**
     * ListAsyncErrors was called without first promoting the draft.
     *
     * @generated from protobuf enum value: LIST_ERRORS_FOR_PROMOTED_DRAFT_ONLY = 11;
     */
    LIST_ERRORS_FOR_PROMOTED_DRAFT_ONLY = 11
}
// @generated message type with reflection information, may provide speed optimized methods
class CampaignDraftErrorEnum$Type extends MessageType<CampaignDraftErrorEnum> {
    constructor() {
        super("google.ads.googleads.v11.errors.CampaignDraftErrorEnum", []);
    }
    create(value?: PartialMessage<CampaignDraftErrorEnum>): CampaignDraftErrorEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CampaignDraftErrorEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CampaignDraftErrorEnum): CampaignDraftErrorEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: CampaignDraftErrorEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.errors.CampaignDraftErrorEnum
 */
export const CampaignDraftErrorEnum = new CampaignDraftErrorEnum$Type();
