// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/errors/field_mask_error.proto" (package "google.ads.googleads.v11.errors", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing field mask errors.

/**
 * Container for enum describing possible field mask errors.
 *
 * @generated from protobuf message google.ads.googleads.v11.errors.FieldMaskErrorEnum
 */
export interface FieldMaskErrorEnum {
}
/**
 * Enum describing possible field mask errors.
 *
 * @generated from protobuf enum google.ads.googleads.v11.errors.FieldMaskErrorEnum.FieldMaskError
 */
export enum FieldMaskErrorEnum_FieldMaskError {
    /**
     * Enum unspecified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The received error code is not known in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * The field mask must be provided for update operations.
     *
     * @generated from protobuf enum value: FIELD_MASK_MISSING = 5;
     */
    FIELD_MASK_MISSING = 5,
    /**
     * The field mask must be empty for create and remove operations.
     *
     * @generated from protobuf enum value: FIELD_MASK_NOT_ALLOWED = 4;
     */
    FIELD_MASK_NOT_ALLOWED = 4,
    /**
     * The field mask contained an invalid field.
     *
     * @generated from protobuf enum value: FIELD_NOT_FOUND = 2;
     */
    FIELD_NOT_FOUND = 2,
    /**
     * The field mask updated a field with subfields. Fields with subfields may
     * be cleared, but not updated. To fix this, the field mask should select
     * all the subfields of the invalid field.
     *
     * @generated from protobuf enum value: FIELD_HAS_SUBFIELDS = 3;
     */
    FIELD_HAS_SUBFIELDS = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class FieldMaskErrorEnum$Type extends MessageType<FieldMaskErrorEnum> {
    constructor() {
        super("google.ads.googleads.v11.errors.FieldMaskErrorEnum", []);
    }
    create(value?: PartialMessage<FieldMaskErrorEnum>): FieldMaskErrorEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<FieldMaskErrorEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FieldMaskErrorEnum): FieldMaskErrorEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: FieldMaskErrorEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.errors.FieldMaskErrorEnum
 */
export const FieldMaskErrorEnum = new FieldMaskErrorEnum$Type();
