// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/errors/manager_link_error.proto" (package "google.ads.googleads.v11.errors", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing ManagerLink errors.

/**
 * Container for enum describing possible ManagerLink errors.
 *
 * @generated from protobuf message google.ads.googleads.v11.errors.ManagerLinkErrorEnum
 */
export interface ManagerLinkErrorEnum {
}
/**
 * Enum describing possible ManagerLink errors.
 *
 * @generated from protobuf enum google.ads.googleads.v11.errors.ManagerLinkErrorEnum.ManagerLinkError
 */
export enum ManagerLinkErrorEnum_ManagerLinkError {
    /**
     * Enum unspecified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The received error code is not known in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * The manager and client have incompatible account types.
     *
     * @generated from protobuf enum value: ACCOUNTS_NOT_COMPATIBLE_FOR_LINKING = 2;
     */
    ACCOUNTS_NOT_COMPATIBLE_FOR_LINKING = 2,
    /**
     * Client is already linked to too many managers.
     *
     * @generated from protobuf enum value: TOO_MANY_MANAGERS = 3;
     */
    TOO_MANY_MANAGERS = 3,
    /**
     * Manager has too many pending invitations.
     *
     * @generated from protobuf enum value: TOO_MANY_INVITES = 4;
     */
    TOO_MANY_INVITES = 4,
    /**
     * Client is already invited by this manager.
     *
     * @generated from protobuf enum value: ALREADY_INVITED_BY_THIS_MANAGER = 5;
     */
    ALREADY_INVITED_BY_THIS_MANAGER = 5,
    /**
     * The client is already managed by this manager.
     *
     * @generated from protobuf enum value: ALREADY_MANAGED_BY_THIS_MANAGER = 6;
     */
    ALREADY_MANAGED_BY_THIS_MANAGER = 6,
    /**
     * Client is already managed in hierarchy.
     *
     * @generated from protobuf enum value: ALREADY_MANAGED_IN_HIERARCHY = 7;
     */
    ALREADY_MANAGED_IN_HIERARCHY = 7,
    /**
     * Manager and sub-manager to be linked have duplicate client.
     *
     * @generated from protobuf enum value: DUPLICATE_CHILD_FOUND = 8;
     */
    DUPLICATE_CHILD_FOUND = 8,
    /**
     * Client has no active user that can access the client account.
     *
     * @generated from protobuf enum value: CLIENT_HAS_NO_ADMIN_USER = 9;
     */
    CLIENT_HAS_NO_ADMIN_USER = 9,
    /**
     * Adding this link would exceed the maximum hierarchy depth.
     *
     * @generated from protobuf enum value: MAX_DEPTH_EXCEEDED = 10;
     */
    MAX_DEPTH_EXCEEDED = 10,
    /**
     * Adding this link will create a cycle.
     *
     * @generated from protobuf enum value: CYCLE_NOT_ALLOWED = 11;
     */
    CYCLE_NOT_ALLOWED = 11,
    /**
     * Manager account has the maximum number of linked clients.
     *
     * @generated from protobuf enum value: TOO_MANY_ACCOUNTS = 12;
     */
    TOO_MANY_ACCOUNTS = 12,
    /**
     * Parent manager account has the maximum number of linked clients.
     *
     * @generated from protobuf enum value: TOO_MANY_ACCOUNTS_AT_MANAGER = 13;
     */
    TOO_MANY_ACCOUNTS_AT_MANAGER = 13,
    /**
     * The account is not authorized owner.
     *
     * @generated from protobuf enum value: NON_OWNER_USER_CANNOT_MODIFY_LINK = 14;
     */
    NON_OWNER_USER_CANNOT_MODIFY_LINK = 14,
    /**
     * Your manager account is suspended, and you are no longer allowed to link
     * to clients.
     *
     * @generated from protobuf enum value: SUSPENDED_ACCOUNT_CANNOT_ADD_CLIENTS = 15;
     */
    SUSPENDED_ACCOUNT_CANNOT_ADD_CLIENTS = 15,
    /**
     * You are not allowed to move a client to a manager that is not under your
     * current hierarchy.
     *
     * @generated from protobuf enum value: CLIENT_OUTSIDE_TREE = 16;
     */
    CLIENT_OUTSIDE_TREE = 16,
    /**
     * The changed status for mutate link is invalid.
     *
     * @generated from protobuf enum value: INVALID_STATUS_CHANGE = 17;
     */
    INVALID_STATUS_CHANGE = 17,
    /**
     * The change for mutate link is invalid.
     *
     * @generated from protobuf enum value: INVALID_CHANGE = 18;
     */
    INVALID_CHANGE = 18,
    /**
     * You are not allowed to link a manager account to itself.
     *
     * @generated from protobuf enum value: CUSTOMER_CANNOT_MANAGE_SELF = 19;
     */
    CUSTOMER_CANNOT_MANAGE_SELF = 19,
    /**
     * The link was created with status ACTIVE and not PENDING.
     *
     * @generated from protobuf enum value: CREATING_ENABLED_LINK_NOT_ALLOWED = 20;
     */
    CREATING_ENABLED_LINK_NOT_ALLOWED = 20
}
// @generated message type with reflection information, may provide speed optimized methods
class ManagerLinkErrorEnum$Type extends MessageType<ManagerLinkErrorEnum> {
    constructor() {
        super("google.ads.googleads.v11.errors.ManagerLinkErrorEnum", []);
    }
    create(value?: PartialMessage<ManagerLinkErrorEnum>): ManagerLinkErrorEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ManagerLinkErrorEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ManagerLinkErrorEnum): ManagerLinkErrorEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ManagerLinkErrorEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.errors.ManagerLinkErrorEnum
 */
export const ManagerLinkErrorEnum = new ManagerLinkErrorEnum$Type();
