// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "ads/errors/user_list_error.proto" (package "google.ads.googleads.v11.errors", syntax proto3)
// tslint:disable
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Proto file describing user list errors.

/**
 * Container for enum describing possible user list errors.
 *
 * @generated from protobuf message google.ads.googleads.v11.errors.UserListErrorEnum
 */
export interface UserListErrorEnum {
}
/**
 * Enum describing possible user list errors.
 *
 * @generated from protobuf enum google.ads.googleads.v11.errors.UserListErrorEnum.UserListError
 */
export enum UserListErrorEnum_UserListError {
    /**
     * Enum unspecified.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * The received error code is not known in this version.
     *
     * @generated from protobuf enum value: UNKNOWN = 1;
     */
    UNKNOWN = 1,
    /**
     * Creating and updating external remarketing user lists is not supported.
     *
     * @generated from protobuf enum value: EXTERNAL_REMARKETING_USER_LIST_MUTATE_NOT_SUPPORTED = 2;
     */
    EXTERNAL_REMARKETING_USER_LIST_MUTATE_NOT_SUPPORTED = 2,
    /**
     * Concrete type of user list is required.
     *
     * @generated from protobuf enum value: CONCRETE_TYPE_REQUIRED = 3;
     */
    CONCRETE_TYPE_REQUIRED = 3,
    /**
     * Creating/updating user list conversion types requires specifying the
     * conversion type Id.
     *
     * @generated from protobuf enum value: CONVERSION_TYPE_ID_REQUIRED = 4;
     */
    CONVERSION_TYPE_ID_REQUIRED = 4,
    /**
     * Remarketing user list cannot have duplicate conversion types.
     *
     * @generated from protobuf enum value: DUPLICATE_CONVERSION_TYPES = 5;
     */
    DUPLICATE_CONVERSION_TYPES = 5,
    /**
     * Conversion type is invalid/unknown.
     *
     * @generated from protobuf enum value: INVALID_CONVERSION_TYPE = 6;
     */
    INVALID_CONVERSION_TYPE = 6,
    /**
     * User list description is empty or invalid.
     *
     * @generated from protobuf enum value: INVALID_DESCRIPTION = 7;
     */
    INVALID_DESCRIPTION = 7,
    /**
     * User list name is empty or invalid.
     *
     * @generated from protobuf enum value: INVALID_NAME = 8;
     */
    INVALID_NAME = 8,
    /**
     * Type of the UserList does not match.
     *
     * @generated from protobuf enum value: INVALID_TYPE = 9;
     */
    INVALID_TYPE = 9,
    /**
     * Embedded logical user lists are not allowed.
     *
     * @generated from protobuf enum value: CAN_NOT_ADD_LOGICAL_LIST_AS_LOGICAL_LIST_OPERAND = 10;
     */
    CAN_NOT_ADD_LOGICAL_LIST_AS_LOGICAL_LIST_OPERAND = 10,
    /**
     * User list rule operand is invalid.
     *
     * @generated from protobuf enum value: INVALID_USER_LIST_LOGICAL_RULE_OPERAND = 11;
     */
    INVALID_USER_LIST_LOGICAL_RULE_OPERAND = 11,
    /**
     * Name is already being used for another user list for the account.
     *
     * @generated from protobuf enum value: NAME_ALREADY_USED = 12;
     */
    NAME_ALREADY_USED = 12,
    /**
     * Name is required when creating a new conversion type.
     *
     * @generated from protobuf enum value: NEW_CONVERSION_TYPE_NAME_REQUIRED = 13;
     */
    NEW_CONVERSION_TYPE_NAME_REQUIRED = 13,
    /**
     * The given conversion type name has been used.
     *
     * @generated from protobuf enum value: CONVERSION_TYPE_NAME_ALREADY_USED = 14;
     */
    CONVERSION_TYPE_NAME_ALREADY_USED = 14,
    /**
     * Only an owner account may edit a user list.
     *
     * @generated from protobuf enum value: OWNERSHIP_REQUIRED_FOR_SET = 15;
     */
    OWNERSHIP_REQUIRED_FOR_SET = 15,
    /**
     * Creating user list without setting type in oneof user_list field, or
     * creating/updating read-only user list types is not allowed.
     *
     * @generated from protobuf enum value: USER_LIST_MUTATE_NOT_SUPPORTED = 16;
     */
    USER_LIST_MUTATE_NOT_SUPPORTED = 16,
    /**
     * Rule is invalid.
     *
     * @generated from protobuf enum value: INVALID_RULE = 17;
     */
    INVALID_RULE = 17,
    /**
     * The specified date range is empty.
     *
     * @generated from protobuf enum value: INVALID_DATE_RANGE = 27;
     */
    INVALID_DATE_RANGE = 27,
    /**
     * A UserList which is privacy sensitive or legal rejected cannot be mutated
     * by external users.
     *
     * @generated from protobuf enum value: CAN_NOT_MUTATE_SENSITIVE_USERLIST = 28;
     */
    CAN_NOT_MUTATE_SENSITIVE_USERLIST = 28,
    /**
     * Maximum number of rulebased user lists a customer can have.
     *
     * @generated from protobuf enum value: MAX_NUM_RULEBASED_USERLISTS = 29;
     */
    MAX_NUM_RULEBASED_USERLISTS = 29,
    /**
     * BasicUserList's billable record field cannot be modified once it is set.
     *
     * @generated from protobuf enum value: CANNOT_MODIFY_BILLABLE_RECORD_COUNT = 30;
     */
    CANNOT_MODIFY_BILLABLE_RECORD_COUNT = 30,
    /**
     * crm_based_user_list.app_id field must be set when upload_key_type is
     * MOBILE_ADVERTISING_ID.
     *
     * @generated from protobuf enum value: APP_ID_NOT_SET = 31;
     */
    APP_ID_NOT_SET = 31,
    /**
     * Name of the user list is reserved for system generated lists and cannot
     * be used.
     *
     * @generated from protobuf enum value: USERLIST_NAME_IS_RESERVED_FOR_SYSTEM_LIST = 32;
     */
    USERLIST_NAME_IS_RESERVED_FOR_SYSTEM_LIST = 32,
    /**
     * Advertiser needs to be on the allow-list to use remarketing lists created
     * from advertiser uploaded data (for example, Customer Match lists).
     *
     * @generated from protobuf enum value: ADVERTISER_NOT_ON_ALLOWLIST_FOR_USING_UPLOADED_DATA = 37;
     */
    ADVERTISER_NOT_ON_ALLOWLIST_FOR_USING_UPLOADED_DATA = 37,
    /**
     * The provided rule_type is not supported for the user list.
     *
     * @generated from protobuf enum value: RULE_TYPE_IS_NOT_SUPPORTED = 34;
     */
    RULE_TYPE_IS_NOT_SUPPORTED = 34,
    /**
     * Similar user list cannot be used as a logical user list operand.
     *
     * @generated from protobuf enum value: CAN_NOT_ADD_A_SIMILAR_USERLIST_AS_LOGICAL_LIST_OPERAND = 35;
     */
    CAN_NOT_ADD_A_SIMILAR_USERLIST_AS_LOGICAL_LIST_OPERAND = 35,
    /**
     * Logical user list should not have a mix of CRM based user list and other
     * types of lists in its rules.
     *
     * @generated from protobuf enum value: CAN_NOT_MIX_CRM_BASED_IN_LOGICAL_LIST_WITH_OTHER_LISTS = 36;
     */
    CAN_NOT_MIX_CRM_BASED_IN_LOGICAL_LIST_WITH_OTHER_LISTS = 36
}
// @generated message type with reflection information, may provide speed optimized methods
class UserListErrorEnum$Type extends MessageType<UserListErrorEnum> {
    constructor() {
        super("google.ads.googleads.v11.errors.UserListErrorEnum", []);
    }
    create(value?: PartialMessage<UserListErrorEnum>): UserListErrorEnum {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UserListErrorEnum>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserListErrorEnum): UserListErrorEnum {
        return target ?? this.create();
    }
    internalBinaryWrite(message: UserListErrorEnum, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message google.ads.googleads.v11.errors.UserListErrorEnum
 */
export const UserListErrorEnum = new UserListErrorEnum$Type();
